#!/usr/bin/env node
/* scripts/lint-refs.js — cross-reference linter for the data↔engine contract.
 *
 * All Edha automation is joined by strings: authored `events` rules name an engine handler
 * type, and the engine names talents it automates. Nothing in Foundry errors when either side
 * dangles — a typo'd handler type silently does nothing (the "silent manual card" failure mode
 * iron rule 3 exists to kill), and a talent renamed in an extract silently orphans its
 * engine automation. This linter machine-checks those joints:
 *
 *   1. Authored file shape — top-level keys, and each talent restricted to the overlay
 *      whitelist (docId/img/description/activation/damage/events/effects — per CLAUDE.md).
 *   2. Every `edha-*` event name and handler `type`, every handler `kind`, and every
 *      non-empty `statusId` used in data/authored/*.json appears as a quoted literal in
 *      register-skills.js (i.e. some dispatch/consumer site exists).
 *   3. Every talent-name literal the engine compares against (`.name === "X"`,
 *      `edhaOwnsTalent(actor, "X")`, `edhaCharacterOwnersOf("X")`) resolves to a talent in
 *      data/authored/* or the structure files — or is on the explicit non-talent allowlist.
 *
 * Zero dependencies. Exit 0 clean, 1 on any error. Runs in CI next to validate.js; add it to
 * the local gates when a change touches authored events or engine name-based automation.
 */
"use strict";
const fs = require("fs");
const path = require("path");
const { parseHandlerSchemas } = require("./handler-schemas.js");

const REPO_ROOT = path.resolve(__dirname, "..");
const ENGINE_PATH = path.join(REPO_ROOT, "module-src", "scripts", "register-skills.js");
const AUTHORED_DIR = path.join(REPO_ROOT, "data", "authored");

// Talent overlay whitelist (CLAUDE.md: "description, activation, damage, events, effects, img
// ONLY" — plus docId, the extract's document id).
const TALENT_KEYS = new Set(["docId", "img", "description", "activation", "damage", "events", "effects"]);
const TOP_KEYS = new Set(["_meta", "talents"]);

// Engine name-literals that are NOT talents — each entry says what it really is.
const NAME_ALLOWLIST = new Set([
  "Draw Mana",     // cosmere-rpg system action item (the leyline Draw Mana riders key off it)
  "Edha Summons",  // the engine's own summon folder name (edhaEnsureSummonFolder)
  "Food (ration, 1 day)",  // edha-items GEAR name (the kit grant's rations lookup) — not a talent
  "Edha PCs",      // the creation wizard's actor-sidebar FOLDER name (edhaCreatorNewCharacter)
]);

const engine = fs.readFileSync(ENGINE_PATH, "utf8");
const errors = [];
const err = (m) => errors.push(m);

// The cosmere-rpg SYSTEM registers its own event vocabulary; authored rules may use it alongside
// the module's edha-* types. Without this, a typo'd native type ("update-acter") passed every gate
// and silently did nothing — the exact failure mode pass 2 exists to kill, just on the half of the
// vocabulary the linter used to be blind to (2026-07-24; see EDHA_EDITABILITY_AUDIT.md §9j).
// Snapshot is generated by scripts/dump-native-vocabulary.js from Ben's Foundry install.
let NATIVE_EVENTS = null, NATIVE_HANDLERS = null, NATIVE_SCHEMA_FIELDS = null;
{
  const p = path.join(REPO_ROOT, "data", "native-vocabulary.json");
  try {
    const v = JSON.parse(fs.readFileSync(p, "utf8"));
    NATIVE_EVENTS = new Set((v.events || []).map((e) => e.type));
    NATIVE_HANDLERS = new Set((v.handlers || []).map((h) => h.type));
    // schemaFields (camelCase, from the system bundle) is the authoring surface pass 9 checks.
    // A pre-07-26 snapshot lacks it — then native FIELD checking is skipped, never guessed
    // (the PascalCase labelKeys are editor chrome and would false-error every correct rule).
    if ((v.handlers || []).every((h) => Array.isArray(h.schemaFields))) {
      NATIVE_SCHEMA_FIELDS = new Map(v.handlers.map((h) => [h.type, new Set(h.schemaFields)]));
    } else {
      console.warn("⚠ lint-refs: native-vocabulary.json predates schemaFields — native FIELD checking skipped. Regenerate with: node scripts/dump-native-vocabulary.js");
    }
  } catch (e) {
    console.warn(`⚠ lint-refs: data/native-vocabulary.json unreadable (${e.message}) — native-type checking SKIPPED. Regenerate with: node scripts/dump-native-vocabulary.js`);
  }
}

// Quoted-literal presence in the engine ('x' or "x" or `x`).
function inEngine(lit) {
  return engine.includes(`"${lit}"`) || engine.includes(`'${lit}'`) || engine.includes("`" + lit + "`");
}

// --- pass 1+2: authored files -------------------------------------------------
const talentNames = new Set();
for (const file of fs.readdirSync(AUTHORED_DIR).filter((f) => f.endsWith(".json")).sort()) {
  const rel = `data/authored/${file}`;
  let doc;
  try { doc = JSON.parse(fs.readFileSync(path.join(AUTHORED_DIR, file), "utf8")); }
  catch (e) { err(`${rel}: invalid JSON — ${e.message}`); continue; }

  for (const k of Object.keys(doc)) if (!TOP_KEYS.has(k)) err(`${rel}: unexpected top-level key "${k}"`);
  const talents = doc.talents || {};
  for (const [name, t] of Object.entries(talents)) {
    talentNames.add(name);
    for (const k of Object.keys(t)) {
      if (!TALENT_KEYS.has(k)) err(`${rel} (${name}): key "${k}" outside the authored-overlay whitelist [${[...TALENT_KEYS].join(", ")}]`);
    }
    for (const [evId, ev] of Object.entries(t.events || {})) {
      // The system's event-rule `id` is a Foundry DocumentIdField — anything that isn't exactly
      // 16 alphanumeric chars fails document validation and the rule is SILENTLY dropped (the
      // 07-12 pass-3b Cruel Step bug: "CruelStepMove01" was 15 chars and the talent went inert).
      if (!/^[a-zA-Z0-9]{16}$/.test(evId)) {
        err(`${rel} (${name}) event ${evId}: rule id must be exactly 16 alphanumeric chars (Foundry DocumentIdField) — the system silently drops invalid rules`);
      }
      if (ev?.id !== evId) {
        err(`${rel} (${name}) event ${evId}: inner "id" (${ev?.id}) doesn't match the rule key`);
      }
      const evName = ev?.event;
      if (typeof evName === "string" && evName) {
        if (evName.startsWith("edha-")) {
          if (!inEngine(evName)) err(`${rel} (${name}) event ${evId}: event "${evName}" has no dispatch site in register-skills.js`);
        } else if (NATIVE_EVENTS && !NATIVE_EVENTS.has(evName)) {
          err(`${rel} (${name}) event ${evId}: event "${evName}" is neither an edha-* event nor one the cosmere-rpg system registers ` +
              `(native: ${[...NATIVE_EVENTS].sort().join(", ")}). A typo here fails SILENTLY at the table.`);
        }
      }
      const h = ev?.handler || {};
      const type = h.type;
      if (typeof type === "string" && type) {
        if (type.startsWith("edha-")) {
          if (!inEngine(type)) err(`${rel} (${name}) event ${evId}: handler type "${type}" has no dispatch site in register-skills.js`);
        } else if (NATIVE_HANDLERS && !NATIVE_HANDLERS.has(type)) {
          err(`${rel} (${name}) event ${evId}: handler type "${type}" is neither an edha-* handler nor one the cosmere-rpg system registers ` +
              `(native: ${[...NATIVE_HANDLERS].sort().join(", ")}). A typo here fails SILENTLY at the table.`);
        }
      }
      if (typeof h.kind === "string" && h.kind && !inEngine(h.kind)) {
        err(`${rel} (${name}) event ${evId}: handler kind "${h.kind}" is not consumed anywhere in register-skills.js`);
      }
      if (typeof h.statusId === "string" && h.statusId && !inEngine(h.statusId)) {
        err(`${rel} (${name}) event ${evId}: statusId "${h.statusId}" is unknown to register-skills.js (typo?)`);
      }
    }
  }
}

// --- the full talent-name universe (authored + the three structure files) ------
for (const rel of ["data/leyline.json", "data/domain.json", "data/cosmere.json"]) {
  let rows;
  try { rows = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, rel), "utf8")); }
  catch (e) { err(`${rel}: invalid JSON — ${e.message}`); continue; }
  for (const r of rows) {
    const n = r?.name || r?.["Talent Name"] || r?.Name;
    if (typeof n === "string" && n.trim()) talentNames.add(n.trim());
  }
}
// Snapshot the TREE-talent universe before adversary abilities join it. Pass 7 (the iron-rule-2b
// ratchet) must use this narrower set: rule 2b governs the talents Ben edits in the talent trees,
// whereas a bespoke adversary ability is a different surface with its own wiring standard
// (pass 5 below) and engine name-keyed automation against one — The Seeming — is legitimate there.
const treeTalentNames = new Set(talentNames);

// Bespoke adversary abilities (data/adversaries.json items) are talents for automation purposes
// since 07-16: foundry-build flags trait/action kinds `adversaryTalent`, so engine name-keyed
// automation (The Seeming) legitimately targets them — they join the resolvable-name universe.
{
  const rel = "data/adversaries.json";
  try {
    const advData = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, rel), "utf8"));
    for (const [advName, adv] of Object.entries(advData)) {
      if (advName.startsWith("_")) continue;
      for (const it of adv.items || []) {
        if (it?.kind !== "weapon" && typeof it?.name === "string" && it.name.trim()) talentNames.add(it.name.trim());
        // Bespoke-ability event rules (simplified array form) join the same data↔engine checks
        // as authored talents — a typo'd handler type on an adversary is the identical silent
        // failure mode.
        for (const [j, ev] of (Array.isArray(it?.events) ? it.events : []).entries()) {
          const where = `${rel} (${advName} / ${it.name}) events[${j}]`;
          const evName = ev?.event;
          if (typeof evName === "string" && evName.startsWith("edha-") && !inEngine(evName)) {
            err(`${where}: event "${evName}" has no dispatch site in register-skills.js`);
          }
          const h = ev?.handler || {};
          if (typeof h.type === "string" && h.type.startsWith("edha-") && !inEngine(h.type)) {
            err(`${where}: handler type "${h.type}" has no dispatch site in register-skills.js`);
          }
          if (typeof h.kind === "string" && h.kind && !inEngine(h.kind)) {
            err(`${where}: handler kind "${h.kind}" is not consumed anywhere in register-skills.js`);
          }
          if (typeof h.statusId === "string" && h.statusId && !inEngine(h.statusId)) {
            err(`${where}: statusId "${h.statusId}" is unknown to register-skills.js (typo?)`);
          }
        }
      }
    }
  } catch (e) { err(`${rel}: invalid JSON — ${e.message}`); }
}

// --- pass 3: engine name-literals must resolve --------------------------------
const nameLits = new Map(); // literal -> first line number
function collect(re) {
  let m;
  while ((m = re.exec(engine)) !== null) {
    const lit = m[1];
    if (!nameLits.has(lit)) nameLits.set(lit, engine.slice(0, m.index).split("\n").length);
  }
}
collect(/\.name\s*(?:===|!==)\s*"([^"]+)"/g);
collect(/edhaOwnsTalent\([^,()]+,\s*"([^"]+)"\)/g);
collect(/edhaCharacterOwnersOf\("([^"]+)"\)/g);

for (const [lit, line] of [...nameLits.entries()].sort((a, b) => a[1] - b[1])) {
  if (talentNames.has(lit) || NAME_ALLOWLIST.has(lit)) continue;
  err(`register-skills.js:${line}: name literal "${lit}" resolves to no talent in data/ ` +
      `(renamed in an extract? if it's genuinely not a talent, add it to NAME_ALLOWLIST in scripts/lint-refs.js with a reason)`);
}

// --- pass 5: no silent manual adversary cards (Ben's 07-16 wiring standard) ----
// An adversary ability whose text names a trigger must carry native automation, an events rule,
// name-keyed engine wiring, or an explicit "NO NAMEABLE HOOK: <reason>" line. A bare 'GM-run'
// label is exactly the soft laziness that left The Seeming dead — lint refuses it.
{
  const TRIGGER_RE = /\bwhen(ever)?\b|\btriggered\b|\beach time\b|\bevery \d|\bfirst time\b|\bon a hit\b|\breduced below\b|\bdrops? to\b|\ban ally drops\b/i;
  try {
    const advData = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, "data/adversaries.json"), "utf8"));
    for (const [advName, adv] of Object.entries(advData)) {
      if (advName.startsWith("_")) continue;
      for (const it of adv.items || []) {
        if (!it || it.kind === "weapon") continue;
        const prose = `${it.text || ""} ${it.rider || ""}`;
        if (!TRIGGER_RE.test(prose)) continue;                          // no trigger named → conscious-use is fine
        if (Array.isArray(it.events) && it.events.length) continue;     // wired via native rules
        if (inEngine(it.name)) continue;                                // name-keyed engine wiring
        if (/NO NAMEABLE HOOK/i.test(prose)) continue;                  // explicit, reasoned exemption
        // The automation lives on ANOTHER item of the same actor (07-19: the Fellstag's Waking
        // Ground rides the auto-embedded Draw Mana's terrain-on-draw). The named carrier must be
        // real: an engine literal (Draw Mana, an aliased talent) — a typo'd carrier is the same
        // silent failure this pass exists to kill.
        const via = prose.match(/ENGINE-NATIVE VIA ([^:<]+):/i);
        if (via) {
          if (inEngine(via[1].trim())) continue;
          err(`data/adversaries.json (${advName} / ${it.name}): ENGINE-NATIVE VIA "${via[1].trim()}" — that carrier isn't a quoted literal in register-skills.js (typo? unwired?)`);
          continue;
        }
        err(`data/adversaries.json (${advName} / ${it.name}): text names a trigger but the ability has no events, ` +
            `no engine name-wiring, and no "NO NAMEABLE HOOK: <reason>" line — wire it or justify it (Ben 07-16)`);
      }
    }
  } catch (e) { /* reported by the earlier adversaries.json pass */ }
}

// --- pass 6: cue triggers must be DISPATCHABLE (the 07-19 dead-wiring family) --
// Handler-type presence (pass 2) can't catch a gm-cue whose `trigger` value nothing sweeps:
// "attack-hit" passed every gate and would never fire at the table (the 07-19 Malcurr audit
// found six such rules, plus two shipped in the 07-19d fens bestiary). The dispatch truth is
// the engine's own edhaCueRules(<actor>, "<trigger>") call sites — extract them, and hold
// every gm-cue rule (adversaries + authored talents) to that vocabulary. Hit cues are a
// different SHAPE, not a trigger: event "edha-on-hit" (and they only fire when the owner
// actually deals damage — a to-hit-only grab has no hook at all; that's a NO NAMEABLE HOOK).
{
  const dispatched = new Set();
  for (const m of engine.matchAll(/edhaCueRules\([^,()]+,\s*"([a-z-]+)"\)/g)) dispatched.add(m[1]);
  if (!dispatched.size) err("pass 6: no edhaCueRules call sites found in register-skills.js — extraction regex rotted?");
  const checkRule = (where, ev) => {
    const h = ev?.handler || {};
    if (h.type !== "edha-gm-cue") return;
    const evName = ev?.event, trig = h.trigger || "damaged";
    if (evName === "edha-on-hit") {
      // The on-hit dispatch keys on the EVENT and ignores handler.trigger entirely (three shipped
      // heroic talents carry the authoring default "damaged" here and work fine) — nothing to lint.
    } else if (evName === "edha-apply-watch") {
      if (!dispatched.has(trig)) {
        err(`${where}: gm-cue trigger "${trig}" is never dispatched (engine sweeps: ${[...dispatched].sort().join(", ")}). ` +
            `A hit cue is event "edha-on-hit" + trigger "on-hit"; a miss or damage-less hit has NO hook — use a "NO NAMEABLE HOOK: <reason>" line instead`);
      }
    } else {
      err(`${where}: gm-cue rules ride event "edha-apply-watch" (or "edha-on-hit" for hit cues) — got "${evName}"`);
    }
  };
  // whenTargetFooled preconditions: the rider reads a belief ledger only a seeming source writes —
  // an item named "The Seeming" (phantom loop) or an edha-ambush-belief rule on the same actor.
  const checkFooled = (where, ev, siblingItems) => {
    if (!ev?.handler?.whenTargetFooled) return;
    const hasSource = (siblingItems || []).some((s) =>
      s?.name === "The Seeming" ||
      (Array.isArray(s?.events) && s.events.some((e) => e?.handler?.type === "edha-ambush-belief")));
    if (!hasSource) {
      err(`${where}: whenTargetFooled rider but this adversary has no seeming source — no item named ` +
          `"The Seeming" and no edha-ambush-belief rule; the ledger is never written, so the rider can never apply`);
    }
  };
  try {
    const advData = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, "data/adversaries.json"), "utf8"));
    for (const [advName, adv] of Object.entries(advData)) {
      if (advName.startsWith("_")) continue;
      for (const it of adv.items || []) {
        for (const [j, ev] of (Array.isArray(it?.events) ? it.events : []).entries()) {
          const where = `data/adversaries.json (${advName} / ${it.name}) events[${j}]`;
          checkRule(where, ev);
          checkFooled(where, ev, adv.items);
        }
      }
    }
  } catch (e) { /* reported by the earlier adversaries.json pass */ }
  for (const file of fs.readdirSync(AUTHORED_DIR).filter((f) => f.endsWith(".json")).sort()) {
    let doc;
    try { doc = JSON.parse(fs.readFileSync(path.join(AUTHORED_DIR, file), "utf8")); } catch (e) { continue; }
    for (const [name, t] of Object.entries(doc.talents || {})) {
      for (const [evId, ev] of Object.entries(t.events || {})) {
        checkRule(`data/authored/${file} (${name}) event ${evId}`, ev);
      }
    }
  }
}

// --- pass 4: no raw talent-type gates (the unreachable-case family, 07-16) -----
// The Seeming's engine case was dead code for two days because a `useItem` hook gated on
// `item.type !== "talent"` while adversary abilities are action-typed twins/bespoke items.
// Every talent-type comparison must go through `edhaIsTalent(...)`; a deliberately strict
// site (PC talent budget, ⟳ Sync, pack scans) carries a `type-strict` marker comment.
engine.split("\n").forEach((lineText, i) => {
  if (!/[?.]type\s*[!=]==\s*["']talent["']/.test(lineText)) return;
  if (lineText.includes("type-strict")) return;
  err(`register-skills.js:${i + 1}: raw talent-type comparison — use edhaIsTalent(...) so adversary ` +
      `abilities (action-typed, adversaryTalent-flagged) aren't silently excluded; if strictness is ` +
      `deliberate, add a "type-strict: <reason>" comment on the line`);
});

// --- pass 8: the `execute-macro` budget (Ben's 07-24p ruling, gate landed 07-24s) ---------------
//
// Ben overruled a flat ban on the system's native `execute-macro` handler, and was right to: a macro
// STRING is testable in a way a "the table resolves this by hand" card never is — a gate can parse
// it and reason about its size. So it is permitted on a shipped talent, GATED. What it must never
// become is the thing iron rule 2a forbids: a cross-actor subsystem living in a text field, i.e. a
// second engine in a string.
//
// This lands BEFORE the first consumer, deliberately (Ben, 07-24r: "a prerequisite, not a
// nice-to-have"). There are zero `execute-macro` rules in data/ today, so nothing is grandfathered
// and the first one written is checked on the way in.
//
// THE LIMITS, and why these numbers. Ben sketched "~15 lines" and left the final call here.
//   · 20 LOGICAL LINES (blank lines and comment-only lines don't count). 15 was the right order of
//     magnitude but too tight in practice for the guard-clause style used everywhere else in this
//     project — `if (!actor) return;` lines are cheap and make code MORE readable, and a limit that
//     punishes them pushes authors toward dense one-liners, which is the opposite of the goal.
//   · 1200 CHARACTERS as well, because a line limit alone is evaded by one long line and a
//     character limit alone is evaded by whitespace. Either bound alone is decorative.
// Both are about SIZE only. They are not a claim that a 20-line macro is a good idea; they are the
// point past which "put it in a handler" stops being a matter of taste.
{
  const MAX_LOGICAL_LINES = 20;
  const MAX_CHARS = 1200;
  // A macro body runs as an async function body in Foundry, so top-level `await` is legal there and
  // must not read as a syntax error here.
  const AsyncFunction = Object.getPrototypeOf(async function () {}).constructor;

  // FIELD SHAPE (corrected 2026-07-26). The system's real execute-macro schema is `inline`
  // (BOOLEAN), `uuid`, and `macro: { type, command }` — camelCase, the macro source living in
  // macro.command. The first version of this pass read `h.Inline` / `h.MacroType` / `h.UUID`,
  // which are the PascalCase i18n LABEL keys from lang/en.json, not schema fields: it would have
  // false-failed every valid inline macro ("empty Inline body") and waved a UUID macro through.
  // Zero consumers existed, so nothing broke — but the gate was aimed at fields that don't exist.
  const checkMacro = (where, h) => {
    // A macro pointed at by UUID lives in the WORLD, not the repo: this gate cannot read it, a
    // reviewer cannot diff it, and a pack rebuild cannot carry it. That defeats the whole point of
    // moving behaviour onto the talent, so inline is the only permitted form.
    if (h.uuid || h.inline !== true) {
      err(`${where}: execute-macro must be INLINE (inline: true + macro.command, no uuid). A macro ` +
          `referenced by UUID lives in the world, not in data/ — this gate cannot parse it, a ` +
          `review cannot diff it, and a pack rebuild cannot carry it, so the behaviour is no more ` +
          `visible than the engine branch it replaced`);
    }
    const mtype = h.macro?.type;
    if (mtype && mtype !== "script") {
      err(`${where}: execute-macro macro.type "${mtype}" — only "script" is permitted; a chat ` +
          `macro as a rule payload is a card pretending to be automation`);
    }
    const body = String(h.macro?.command ?? "");
    if (!body.trim()) {
      err(`${where}: execute-macro has an empty macro.command — an empty macro is a talent that does nothing`);
      return;
    }
    if (body.length > MAX_CHARS) {
      err(`${where}: execute-macro macro.command is ${body.length} chars (max ${MAX_CHARS}) — if it ` +
          `needs to be this big it needs to be a handler; see iron rule 2a`);
    }
    const logical = body.split("\n")
      .map((l) => l.trim())
      .filter((l) => l && !l.startsWith("//") && !l.startsWith("*") && !l.startsWith("/*")).length;
    if (logical > MAX_LOGICAL_LINES) {
      err(`${where}: execute-macro macro.command is ${logical} logical lines (max ${MAX_LOGICAL_LINES}; ` +
          `blanks and comments are free) — if it needs to be this big it needs to be a handler`);
    }
    // A parse error means the rule is dead at the table and nothing says so. This is the check that
    // makes a macro defensible at all: it is the thing a manual card can never be given.
    try { new AsyncFunction(body); }
    catch (e) { err(`${where}: execute-macro macro.command does not parse — ${e.message}`); }
    // Size is the wrong thing to worry about on its own. A macro that registers a hook is a SECOND
    // ENGINE regardless of length: it outlives the use that created it, it re-registers on every
    // execution, and nothing ever removes it. Same for a timer.
    if (/\bHooks\s*\.\s*(on|once)\s*\(/.test(body)) {
      err(`${where}: execute-macro macro.command registers a Foundry hook. A hook outlives the use ` +
          `that created it and re-registers every time the macro runs, with nothing to remove it — ` +
          `that is a second engine in a text field whatever its length. Put it in register-skills.js`);
    }
    if (/\bset(Interval|Timeout)\s*\(/.test(body)) {
      err(`${where}: execute-macro macro.command schedules a timer — same problem as a hook: it ` +
          `outlives the use, and nothing cancels it. Put it in register-skills.js`);
    }
  };

  for (const file of fs.readdirSync(AUTHORED_DIR).filter((f) => f.endsWith(".json")).sort()) {
    let doc;
    try { doc = JSON.parse(fs.readFileSync(path.join(AUTHORED_DIR, file), "utf8")); } catch (e) { continue; }
    for (const [name, t] of Object.entries(doc.talents || {})) {
      for (const [evId, ev] of Object.entries(t.events || {})) {
        if (ev?.handler?.type === "execute-macro") checkMacro(`data/authored/${file} (${name}) event ${evId}`, ev.handler);
      }
    }
  }
  try {
    const advData = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, "data/adversaries.json"), "utf8"));
    for (const [advName, adv] of Object.entries(advData)) {
      if (advName.startsWith("_")) continue;
      for (const it of adv.items || []) {
        for (const [j, ev] of (Array.isArray(it?.events) ? it.events : []).entries()) {
          if (ev?.handler?.type === "execute-macro") checkMacro(`data/adversaries.json (${advName} / ${it.name}) events[${j}]`, ev.handler);
        }
      }
    }
  } catch (e) { /* pass 5 already reports a malformed adversaries.json */ }
}

// --- pass 7: the iron-rule-2b RATCHET (2026-07-24) -----------------------------
// Rule 2b: a talent's behaviour belongs on the talent (system.events / effects), not bound to
// its NAME in engine code. A name-keyed talent ships with empty Events/Effects tabs, editing
// them in Foundry does nothing, and renaming it silently unwires it — which is how 200 of 365
// talents came to violate a requirement that no rule had ever been written down to protect.
//
// The 221 talent names the engine mentioned in CODE on 2026-07-24 are frozen in
// scripts/name-keyed-allowlist.json. This pass makes that list a RATCHET: it may shrink, never
// grow. Comments are stripped first, deliberately — the engine's tree-section headers list
// talents by name on purpose (that IS the iron-rule-3 ledger) and must not read as violations.
{
  const ALLOW_PATH = path.join(__dirname, "name-keyed-allowlist.json");
  let allow;
  try { allow = JSON.parse(fs.readFileSync(ALLOW_PATH, "utf8")); }
  catch (e) { err(`pass 7: cannot read scripts/name-keyed-allowlist.json — ${e.message}`); allow = null; }

  if (allow) {
    // Strip block and line comments so only executable code is scanned.
    const stripped = [];
    let inBlock = false;
    for (const raw of engine.split("\n")) {
      let l = raw;
      if (inBlock) { const e = l.indexOf("*/"); if (e < 0) { stripped.push(""); continue; } l = l.slice(e + 2); inBlock = false; }
      for (;;) {
        const b = l.indexOf("/*"); if (b < 0) break;
        const e = l.indexOf("*/", b + 2);
        if (e < 0) { l = l.slice(0, b); inBlock = true; break; }
        l = l.slice(0, b) + " " + l.slice(e + 2);
      }
      const s = l.indexOf("//");
      // only treat // as a comment when it isn't inside a string literal
      if (s >= 0 && (l.slice(0, s).split('"').length - 1) % 2 === 0) l = l.slice(0, s);
      stripped.push(l);
    }

    const listed = new Set(allow.talents || []);
    const found = new Map();   // talent name -> first code line
    stripped.forEach((l, i) => {
      for (const m of l.matchAll(/"([^"\\\n]{3,45})"/g)) {
        if (!treeTalentNames.has(m[1]) || found.has(m[1])) continue;
        /* A `label:` value is a DISPLAY string, never dispatch (07-24u). The status-effect table
         * carries `covenant: { label: "Covenant", … }`, and rule 2b's actual test — "would renaming
         * the talent silently unwire it?" — is NO: the talent's rule references the status ID
         * (`status: "covenant"`, authored data), so a rename leaves a cosmetically stale label and
         * nothing more. Counting it kept Covenant on the ratchet after it had fully converted, which
         * makes the ratchet number FICTION in the safe-looking direction.
         *
         * Deliberately narrow. Measured before landing: this excludes exactly ONE name today
         * (Covenant, register-skills.js:178) and no other talent name in the engine occurs solely as
         * a label. Handler-schema labels are prose and never bare talent names. This is the FOURTH
         * gate the migration has had to teach a new form (audit §9n: audit.py's soft-laziness check,
         * lint pass 5, audit.py's locale codec) — treat the next one as a finding too. */
        if (/label:\s*$/.test(l.slice(0, m.index))) continue;
        found.set(m[1], i + 1);
      }
    });

    const added = [...found.keys()].filter((n) => !listed.has(n)).sort();
    for (const n of added) {
      err(`register-skills.js:${found.get(n)}: IRON RULE 2b — new name-keyed dispatch on "${n}". ` +
          `Behaviour must live on the talent (system.events / effects in data/authored/), not be ` +
          `bound to its name: a name-keyed talent shows EMPTY Events/Effects tabs in Foundry, ` +
          `editing them does nothing, and renaming it silently unwires it. If the mechanic ` +
          `genuinely cannot be a rule, take the declared ENGINE-OWNED exit (cue rule on the talent ` +
          `+ an "ENGINE_OWNED: <reason>" line in the tree-section header) — an exit still keeps the ` +
          `name out of engine code. The allowlist may SHRINK, never grow; do not add "${n}" to it.`);
    }

    const stale = [...listed].filter((n) => !found.has(n)).sort();
    if (stale.length) {
      err(`pass 7: ${stale.length} talent(s) migrated off name-keyed dispatch but still listed in ` +
          `scripts/name-keyed-allowlist.json — delete them so the ratchet reflects reality ` +
          `(${allow.originalCount} at 2026-07-24, ${found.size} now): ${stale.join(", ")}`);
    }
  }
}

// --- pass 9: handler FIELD names must match the registered schema (2026-07-26) --
// Pass 2 checks handler TYPES; nothing checked the field names INSIDE a handler object until the
// pre-deploy audit of the finished 2b migration. Foundry's DataModel silently DROPS any key the
// registered config schema doesn't define: the rule loads, the Events tab renders, and the
// mechanic just never fires — the field-level twin of the failure mode pass 2 kills. 221 talents
// were hand-authored across 27 sessions, so this must be a gate, not a one-off sweep.
// edha-* schemas are parsed from the engine's own registerItemEventHandlerType calls
// (scripts/handler-schemas.js — hard-fails if the parse rots); native schemas come from
// native-vocabulary.json's schemaFields. Rule-level keys are held to the system's rule schema
// too ({id, description, order, event, handler}) — a typo'd "hander" is a dead rule the same way.
{
  let handlerSchemas = null;
  try { handlerSchemas = parseHandlerSchemas(engine); }
  catch (e) { err(`pass 9: cannot parse engine handler schemas — ${e.message}`); }

  const AUTHORED_RULE_KEYS = new Set(["id", "description", "order", "event", "handler"]);
  // foundry-build's simplified adversary form carries ONLY these; anything else (an `order`, an
  // `id`) is silently discarded by the build — the same dropped-on-the-floor failure, one stage
  // earlier in the pipeline.
  const ADVERSARY_RULE_KEYS = new Set(["event", "handler", "description"]);

  const checkFields = (where, h) => {
    if (!handlerSchemas || !h || typeof h.type !== "string" || !h.type) return;
    let fields;
    if (h.type.startsWith("edha-")) {
      if (!handlerSchemas.has(h.type)) {
        err(`${where}: handler type "${h.type}" is never REGISTERED via registerItemEventHandlerType — ` +
            `pass 2's quoted-literal check can be satisfied by a comment or a dispatch string; a ` +
            `registration cannot. The rule is dead at the table.`);
        return;
      }
      fields = handlerSchemas.get(h.type);
    } else if (NATIVE_SCHEMA_FIELDS && NATIVE_SCHEMA_FIELDS.has(h.type)) {
      fields = NATIVE_SCHEMA_FIELDS.get(h.type);
    } else return; // unknown native type is pass 2's report, not ours
    for (const k of Object.keys(h)) {
      if (k === "type" || fields.has(k)) continue;
      err(`${where}: handler "${h.type}" has no field "${k}" — Foundry's DataModel silently drops ` +
          `unknown keys, so the rule loads, the tab looks right, and this key does NOTHING. ` +
          `Registered fields: ${[...fields].sort().join(", ")}`);
    }
  };

  for (const file of fs.readdirSync(AUTHORED_DIR).filter((f) => f.endsWith(".json")).sort()) {
    let doc;
    try { doc = JSON.parse(fs.readFileSync(path.join(AUTHORED_DIR, file), "utf8")); } catch (e) { continue; }
    for (const [name, t] of Object.entries(doc.talents || {})) {
      for (const [evId, ev] of Object.entries(t.events || {})) {
        const where = `data/authored/${file} (${name}) event ${evId}`;
        for (const k of Object.keys(ev || {})) {
          if (!AUTHORED_RULE_KEYS.has(k)) {
            err(`${where}: rule key "${k}" is not in the system's rule schema ` +
                `[${[...AUTHORED_RULE_KEYS].join(", ")}] — it is silently dropped`);
          }
        }
        checkFields(where, ev?.handler);
      }
    }
  }
  try {
    const advData = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, "data/adversaries.json"), "utf8"));
    for (const [advName, adv] of Object.entries(advData)) {
      if (advName.startsWith("_")) continue;
      for (const it of adv.items || []) {
        for (const [j, ev] of (Array.isArray(it?.events) ? it.events : []).entries()) {
          const where = `data/adversaries.json (${advName} / ${it.name}) events[${j}]`;
          for (const k of Object.keys(ev || {})) {
            if (!ADVERSARY_RULE_KEYS.has(k)) {
              err(`${where}: rule key "${k}" is not in the simplified adversary form ` +
                  `[${[...ADVERSARY_RULE_KEYS].join(", ")}] — foundry-build discards it`);
            }
          }
          checkFields(where, ev?.handler);
        }
      }
    }
  } catch (e) { /* reported by the earlier adversaries.json pass */ }
}

// --- report --------------------------------------------------------------------
if (errors.length) {
  for (const e of errors) console.error(`✗ ${e}`);
  console.error(`\n${errors.length} error${errors.length === 1 ? "" : "s"}.`);
  process.exit(1);
}
console.log(`✓ lint-refs: ${talentNames.size} talent names, ${nameLits.size} engine name-literals resolved, authored overlays clean.`);
