#!/usr/bin/env node
/* scripts/lint-refs.js — cross-reference linter for the data↔engine contract.
 *
 * All Edha automation is joined by strings: authored `events` rules name an engine handler
 * type, and the engine names talents it automates. Nothing in Foundry errors when either side
 * dangles — a typo'd handler type silently does nothing (the "silent manual card" failure mode
 * iron rule 3 exists to kill), and a talent renamed in an extract silently orphans its
 * engine automation. This linter machine-checks those joints:
 *
 *   1. Authored file shape — top-level keys, and each talent restricted to the overlay
 *      whitelist (docId/img/description/activation/damage/events/effects — per CLAUDE.md).
 *   2. Every `edha-*` event name and handler `type`, every handler `kind`, and every
 *      non-empty `statusId` used in data/authored/*.json appears as a quoted literal in
 *      register-skills.js (i.e. some dispatch/consumer site exists).
 *   3. Every talent-name literal the engine compares against (`.name === "X"`,
 *      `edhaOwnsTalent(actor, "X")`, `edhaCharacterOwnersOf("X")`) resolves to a talent in
 *      data/authored/* or the structure files — or is on the explicit non-talent allowlist.
 *  11. Every `system.<field>` the engine or the build reads/writes is a field some cosmere
 *      DataModel actually declares (the DEAD-FIELD family — three shipped bugs; see the pass).
 *  12. Every cosmere id an authored rule names — skill, attribute, status, damage type, defense,
 *      and every `@skills.`/`@attr.` ref — exists in the real vocabulary (the DEAD-ID family:
 *      eight talents shipped on `itm`/`per`/`ldr`, all silently inert; see the pass).
 *  13. Every authored value that reaches a closed SYSTEM enum is one of its legal values (the
 *      WRONG-SHAPE family: quarry advantage wrote the number 1 into a string enum and never once
 *      applied. Engine-side coverage lives in tests/advantage-channel.test.js — see the pass).
 *  14. Every item carrying an `edha-def-test` rule can actually ROLL the test it gates, with the
 *      SAME skill (the MUTE-DEF-TEST family: six adversary abilities in 07-26j, then Sharp Eye on
 *      the talent surface in 07-27n — H1 waits for a roll that never comes; see the pass).
 *  15. No hook that WRITES the world is gated on a raw `isGM` (the TWO-GM family: hooks fire on
 *      every client, so per-GM means twice at Ben's table — Apex Form's double injury, the 07-27b
 *      2bW-13 sweep, and bench run 13's double-posted card plus the two more its sweep found).
 *
 * Zero dependencies. Exit 0 clean, 1 on any error. Runs in CI next to validate.js; add it to
 * the local gates when a change touches authored events or engine name-based automation.
 */
"use strict";
const fs = require("fs");
const path = require("path");
const { parseHandlerSchemas, matchBrace, topLevelKeys } = require("./handler-schemas.js");

const REPO_ROOT = path.resolve(__dirname, "..");
const ENGINE_PATH = path.join(REPO_ROOT, "module-src", "scripts", "register-skills.js");
const AUTHORED_DIR = path.join(REPO_ROOT, "data", "authored");

// Talent overlay whitelist (CLAUDE.md: "description, activation, damage, events, effects, img
// ONLY" — plus docId, the extract's document id).
const TALENT_KEYS = new Set(["docId", "img", "description", "activation", "damage", "events", "effects"]);
const TOP_KEYS = new Set(["_meta", "talents"]);

// Engine name-literals that are NOT talents — each entry says what it really is.
const NAME_ALLOWLIST = new Set([
  "Draw Mana",     // cosmere-rpg system action item (the leyline Draw Mana riders key off it)
  "Edha Summons",  // the engine's own summon folder name (edhaEnsureSummonFolder)
  "Food (ration, 1 day)",  // edha-items GEAR name (the kit grant's rations lookup) — not a talent
  "Edha PCs",      // the creation wizard's actor-sidebar FOLDER name (edhaCreatorNewCharacter)
]);

const engine = fs.readFileSync(ENGINE_PATH, "utf8");
const errors = [];
const err = (m) => errors.push(m);

// The cosmere-rpg SYSTEM registers its own event vocabulary; authored rules may use it alongside
// the module's edha-* types. Without this, a typo'd native type ("update-acter") passed every gate
// and silently did nothing — the exact failure mode pass 2 exists to kill, just on the half of the
// vocabulary the linter used to be blind to (2026-07-24; see EDHA_EDITABILITY_AUDIT.md §9j).
// Snapshot is generated by scripts/dump-native-vocabulary.js from Ben's Foundry install.
let NATIVE_EVENTS = null, NATIVE_HANDLERS = null, NATIVE_SCHEMA_FIELDS = null;
{
  const p = path.join(REPO_ROOT, "data", "native-vocabulary.json");
  try {
    const v = JSON.parse(fs.readFileSync(p, "utf8"));
    NATIVE_EVENTS = new Set((v.events || []).map((e) => e.type));
    NATIVE_HANDLERS = new Set((v.handlers || []).map((h) => h.type));
    // schemaFields (camelCase, from the system bundle) is the authoring surface pass 9 checks.
    // A pre-07-26 snapshot lacks it — then native FIELD checking is skipped, never guessed
    // (the PascalCase labelKeys are editor chrome and would false-error every correct rule).
    if ((v.handlers || []).every((h) => Array.isArray(h.schemaFields))) {
      NATIVE_SCHEMA_FIELDS = new Map(v.handlers.map((h) => [h.type, new Set(h.schemaFields)]));
    } else {
      console.warn("⚠ lint-refs: native-vocabulary.json predates schemaFields — native FIELD checking skipped. Regenerate with: node scripts/dump-native-vocabulary.js");
    }
  } catch (e) {
    console.warn(`⚠ lint-refs: data/native-vocabulary.json unreadable (${e.message}) — native-type checking SKIPPED. Regenerate with: node scripts/dump-native-vocabulary.js`);
  }
}

// Quoted-literal presence in the engine ('x' or "x" or `x`).
function inEngine(lit) {
  return engine.includes(`"${lit}"`) || engine.includes(`'${lit}'`) || engine.includes("`" + lit + "`");
}

// Comment-stripped engine source, for checks that must mean "in CODE". The tree-section headers
// list every talent by name (that IS the iron-rule-3 ledger), so a raw inEngine() is satisfied by
// prose — which is how pass 5's name-keyed-wiring exemption went silently vacuous when the 2b
// migration deleted the last tree-talent name from code (2026-07-26: two adversary abilities
// whose cues promised "use the item to auto-resolve" had been dead since their name-key was
// deleted, and pass 5 kept exempting them on the strength of a comment).
function stripComments(src) {
  const out = [];
  let inBlock = false;
  for (const raw of src.split("\n")) {
    let l = raw;
    if (inBlock) { const e = l.indexOf("*/"); if (e < 0) { out.push(""); continue; } l = l.slice(e + 2); inBlock = false; }
    for (;;) {
      const b = l.indexOf("/*"); if (b < 0) break;
      const e = l.indexOf("*/", b + 2);
      if (e < 0) { l = l.slice(0, b); inBlock = true; break; }
      l = l.slice(0, b) + " " + l.slice(e + 2);
    }
    const s = l.indexOf("//");
    // only treat // as a comment when it isn't inside a string literal
    if (s >= 0 && (l.slice(0, s).split('"').length - 1) % 2 === 0) l = l.slice(0, s);
    out.push(l);
  }
  return out.join("\n");
}
const engineCode = stripComments(engine);
/* Comments AND string contents replaced by spaces, byte offsets and line breaks preserved — so a
 * match index in the result still points at the same place in the original. `stripComments` above
 * rebuilds line-by-line and cannot be indexed back into the source; pass 11 needs both (it reads
 * object literals out of the ORIGINAL text at offsets found in the blanked copy).
 *
 * TEMPLATE-AWARE since 07-27y, and that is not a nicety — it was silently disabling this whole
 * file. The old scanner closed a backtick string at the FIRST backtick it saw, so a NESTED template
 * inside `${…}` (the engine has ~30, e.g.
 *     `…${a ? " strike" : `${x.name}'s hit`}…`
 * ) closed the OUTER template early, dumped the remaining string text into "code", and the next
 * apostrophe in prose ("the victim's healing") opened a runaway span that ate real code until the
 * next stray quote. Measured on register-skills.js: 116 runaway spans, 598 code lines (5.9%)
 * blanked to nothing. Every pass built on this helper — 11 (dead fields), 15 (isGM hooks), 16
 * (Region flags), 17 (object-as-scalar) — was blind on those lines, and the hole was invisible
 * because a blind pass reports SUCCESS. Verified by the very bug that exposed it: pass 17 did not
 * see the third object-as-scalar site (register-skills.js:5933) until this was fixed.
 *
 * The scanner is now an explicit context stack: code / quoted-string / template, with `${…}`
 * pushing a fresh CODE frame (brace-counted) so nested templates and the code inside interpolations
 * are both handled. Code inside `${…}` is now EXPOSED to the passes, which is correct — it is code.
 *
 * REGEX LITERALS get the standard prev-token heuristic: a `/` starts a regex when the previous
 * non-space code character cannot end an expression. Without it, `/[&<>"]/` (escCw, one line) opened
 * a fake string on its `"` and swallowed the next 36 lines. The heuristic is not a tokeniser — it
 * mis-reads `a /b/ c` as a regex — but that is division by an identifier on both sides, which does
 * not occur here, and the failure direction is the safe one (blanking too much never invents a
 * violation, it only hides one, and the per-pass rot alarms catch a collapse). */
/* Does the `/` at `i` open a REGEX literal (rather than being division)? The standard heuristic:
 * look back past whitespace at the previous code character — if it cannot END an expression, a
 * regex must follow. `)` is deliberately treated as "can end" (so `(a+b) / c` is division), which
 * mis-reads `if (x) /re/.test(y)`; no such form exists here. */
function regexStartsHere(src, i) {
  let j = i - 1;
  while (j >= 0 && /\s/.test(src[j])) j--;
  if (j < 0) return true;
  const p = src[j];
  if ("([{,;:=!&|?+-*%~^<>".includes(p)) return true;
  return /\b(return|typeof|case|in|of|new|delete|void|do|else|yield|await)$/.test(src.slice(Math.max(0, j - 9), j + 1));
}
function blankStringsAndComments(src, { keepStrings = false } = {}) {
  let out = "";
  const emit = (ch, blankIt) => { out += (ch === "\n") ? "\n" : (blankIt ? " " : ch); };
  const stack = [{ k: "code", braces: 0, root: true }];
  for (let i = 0; i < src.length; ) {
    const t = stack[stack.length - 1];
    const c = src[i];

    if (t.k === "str" || t.k === "tpl") {
      if (c === "\\") { emit(c, !keepStrings); emit(src[i + 1] ?? "", !keepStrings); i += 2; continue; }
      if (c === (t.k === "tpl" ? "`" : t.q)) { out += c; i++; stack.pop(); continue; }   // the delimiter itself stays
      if (t.k === "tpl" && c === "$" && src[i + 1] === "{") {   // interpolation: back to CODE until the matching }
        out += "${"; i += 2; stack.push({ k: "code", braces: 0 }); continue;
      }
      emit(c, !keepStrings); i++; continue;
    }

    // code frame
    if (c === "/" && src[i + 1] === "/") { while (i < src.length && src[i] !== "\n") { emit(src[i], true); i++; } continue; }
    if (c === "/" && src[i + 1] === "*") {
      const e = src.indexOf("*/", i + 2);
      const end = e < 0 ? src.length : e + 2;
      for (; i < end; i++) emit(src[i], true);
      continue;
    }
    if (c === '"' || c === "'") { out += c; i++; stack.push({ k: "str", q: c }); continue; }
    if (c === "`") { out += c; i++; stack.push({ k: "tpl" }); continue; }
    if (c === "/" && regexStartsHere(src, i)) {           // a REGEX literal, not division — skip it whole
      out += c; i++;
      for (let cls = false; i < src.length; i++) {
        if (src[i] === "\\") { out += "  "; i++; continue; }
        if (src[i] === "[") cls = true; else if (src[i] === "]") cls = false;
        const done = src[i] === "/" && !cls;
        out += src[i] === "\n" ? "\n" : (done ? "/" : " ");
        if (done || src[i] === "\n") { i++; break; }       // a newline means it was division after all — bail
      }
      continue;
    }
    if (!t.root) {
      if (c === "{") { t.braces++; out += c; i++; continue; }
      if (c === "}") { out += c; i++; if (t.braces === 0) stack.pop(); else t.braces--; continue; }
    }
    out += c; i++;
  }
  return out;
}
function inEngineCode(lit) {
  return engineCode.includes(`"${lit}"`) || engineCode.includes(`'${lit}'`) || engineCode.includes("`" + lit + "`");
}

// --- pass 1+2: authored files -------------------------------------------------
const talentNames = new Set();
for (const file of fs.readdirSync(AUTHORED_DIR).filter((f) => f.endsWith(".json")).sort()) {
  const rel = `data/authored/${file}`;
  let doc;
  try { doc = JSON.parse(fs.readFileSync(path.join(AUTHORED_DIR, file), "utf8")); }
  catch (e) { err(`${rel}: invalid JSON — ${e.message}`); continue; }

  for (const k of Object.keys(doc)) if (!TOP_KEYS.has(k)) err(`${rel}: unexpected top-level key "${k}"`);
  const talents = doc.talents || {};
  for (const [name, t] of Object.entries(talents)) {
    talentNames.add(name);
    for (const k of Object.keys(t)) {
      if (!TALENT_KEYS.has(k)) err(`${rel} (${name}): key "${k}" outside the authored-overlay whitelist [${[...TALENT_KEYS].join(", ")}]`);
    }
    for (const [evId, ev] of Object.entries(t.events || {})) {
      // The system's event-rule `id` is a Foundry DocumentIdField — anything that isn't exactly
      // 16 alphanumeric chars fails document validation and the rule is SILENTLY dropped (the
      // 07-12 pass-3b Cruel Step bug: "CruelStepMove01" was 15 chars and the talent went inert).
      if (!/^[a-zA-Z0-9]{16}$/.test(evId)) {
        err(`${rel} (${name}) event ${evId}: rule id must be exactly 16 alphanumeric chars (Foundry DocumentIdField) — the system silently drops invalid rules`);
      }
      if (ev?.id !== evId) {
        err(`${rel} (${name}) event ${evId}: inner "id" (${ev?.id}) doesn't match the rule key`);
      }
      const evName = ev?.event;
      if (typeof evName === "string" && evName) {
        if (evName.startsWith("edha-")) {
          if (!inEngine(evName)) err(`${rel} (${name}) event ${evId}: event "${evName}" has no dispatch site in register-skills.js`);
        } else if (NATIVE_EVENTS && !NATIVE_EVENTS.has(evName)) {
          err(`${rel} (${name}) event ${evId}: event "${evName}" is neither an edha-* event nor one the cosmere-rpg system registers ` +
              `(native: ${[...NATIVE_EVENTS].sort().join(", ")}). A typo here fails SILENTLY at the table.`);
        }
      }
      const h = ev?.handler || {};
      const type = h.type;
      if (typeof type === "string" && type) {
        if (type.startsWith("edha-")) {
          if (!inEngine(type)) err(`${rel} (${name}) event ${evId}: handler type "${type}" has no dispatch site in register-skills.js`);
        } else if (NATIVE_HANDLERS && !NATIVE_HANDLERS.has(type)) {
          err(`${rel} (${name}) event ${evId}: handler type "${type}" is neither an edha-* handler nor one the cosmere-rpg system registers ` +
              `(native: ${[...NATIVE_HANDLERS].sort().join(", ")}). A typo here fails SILENTLY at the table.`);
        }
      }
      if (typeof h.kind === "string" && h.kind && !inEngine(h.kind)) {
        err(`${rel} (${name}) event ${evId}: handler kind "${h.kind}" is not consumed anywhere in register-skills.js`);
      }
      if (typeof h.statusId === "string" && h.statusId && !inEngine(h.statusId)) {
        err(`${rel} (${name}) event ${evId}: statusId "${h.statusId}" is unknown to register-skills.js (typo?)`);
      }
    }
  }
}

// --- the full talent-name universe (authored + the three structure files) ------
for (const rel of ["data/leyline.json", "data/domain.json", "data/cosmere.json"]) {
  let rows;
  try { rows = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, rel), "utf8")); }
  catch (e) { err(`${rel}: invalid JSON — ${e.message}`); continue; }
  for (const r of rows) {
    const n = r?.name || r?.["Talent Name"] || r?.Name;
    if (typeof n === "string" && n.trim()) talentNames.add(n.trim());
  }
}
// Snapshot the TREE-talent universe before adversary abilities join it. Pass 7 (the iron-rule-2b
// ratchet) must use this narrower set: rule 2b governs the talents Ben edits in the talent trees,
// whereas a bespoke adversary ability is a different surface with its own wiring standard
// (pass 5 below) and engine name-keyed automation against one — The Seeming — is legitimate there.
const treeTalentNames = new Set(talentNames);

// Bespoke adversary abilities (data/adversaries.json items) are talents for automation purposes
// since 07-16: foundry-build flags trait/action kinds `adversaryTalent`, so engine name-keyed
// automation (The Seeming) legitimately targets them — they join the resolvable-name universe.
{
  const rel = "data/adversaries.json";
  try {
    const advData = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, rel), "utf8"));
    for (const [advName, adv] of Object.entries(advData)) {
      if (advName.startsWith("_")) continue;
      for (const it of adv.items || []) {
        if (it?.kind !== "weapon" && typeof it?.name === "string" && it.name.trim()) talentNames.add(it.name.trim());
        // Bespoke-ability event rules (simplified array form) join the same data↔engine checks
        // as authored talents — a typo'd handler type on an adversary is the identical silent
        // failure mode.
        for (const [j, ev] of (Array.isArray(it?.events) ? it.events : []).entries()) {
          const where = `${rel} (${advName} / ${it.name}) events[${j}]`;
          const evName = ev?.event;
          if (typeof evName === "string" && evName.startsWith("edha-") && !inEngine(evName)) {
            err(`${where}: event "${evName}" has no dispatch site in register-skills.js`);
          }
          const h = ev?.handler || {};
          if (typeof h.type === "string" && h.type.startsWith("edha-") && !inEngine(h.type)) {
            err(`${where}: handler type "${h.type}" has no dispatch site in register-skills.js`);
          }
          if (typeof h.kind === "string" && h.kind && !inEngine(h.kind)) {
            err(`${where}: handler kind "${h.kind}" is not consumed anywhere in register-skills.js`);
          }
          if (typeof h.statusId === "string" && h.statusId && !inEngine(h.statusId)) {
            err(`${where}: statusId "${h.statusId}" is unknown to register-skills.js (typo?)`);
          }
        }
      }
    }
  } catch (e) { err(`${rel}: invalid JSON — ${e.message}`); }
}

// --- pass 3: engine name-literals must resolve --------------------------------
const nameLits = new Map(); // literal -> first line number
function collect(re) {
  let m;
  while ((m = re.exec(engine)) !== null) {
    const lit = m[1];
    if (!nameLits.has(lit)) nameLits.set(lit, engine.slice(0, m.index).split("\n").length);
  }
}
collect(/\.name\s*(?:===|!==)\s*"([^"]+)"/g);
collect(/edhaOwnsTalent\([^,()]+,\s*"([^"]+)"\)/g);
collect(/edhaCharacterOwnersOf\("([^"]+)"\)/g);

for (const [lit, line] of [...nameLits.entries()].sort((a, b) => a[1] - b[1])) {
  if (talentNames.has(lit) || NAME_ALLOWLIST.has(lit)) continue;
  err(`register-skills.js:${line}: name literal "${lit}" resolves to no talent in data/ ` +
      `(renamed in an extract? if it's genuinely not a talent, add it to NAME_ALLOWLIST in scripts/lint-refs.js with a reason)`);
}

// --- pass 5: no silent manual adversary cards (Ben's 07-16 wiring standard) ----
// An adversary ability whose text names a trigger must carry native automation, an events rule,
// name-keyed engine wiring, or an explicit "NO NAMEABLE HOOK: <reason>" line. A bare 'GM-run'
// label is exactly the soft laziness that left The Seeming dead — lint refuses it.
{
  const TRIGGER_RE = /\bwhen(ever)?\b|\btriggered\b|\beach time\b|\bevery \d|\bfirst time\b|\bon a hit\b|\breduced below\b|\bdrops? to\b|\ban ally drops\b/i;
  try {
    const advData = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, "data/adversaries.json"), "utf8"));
    for (const [advName, adv] of Object.entries(advData)) {
      if (advName.startsWith("_")) continue;
      for (const it of adv.items || []) {
        if (!it || it.kind === "weapon") continue;
        const prose = `${it.text || ""} ${it.rider || ""}`;
        if (!TRIGGER_RE.test(prose)) continue;                          // no trigger named → conscious-use is fine
        if (Array.isArray(it.events) && it.events.length) continue;     // wired via native rules
        if (inEngineCode(it.name)) continue;                            // name-keyed engine wiring — CODE only (comments satisfied this for months; see stripComments)
        if (/NO NAMEABLE HOOK/i.test(prose)) continue;                  // explicit, reasoned exemption
        // The automation lives on ANOTHER item of the same actor (07-19: the Fellstag's Waking
        // Ground rides the auto-embedded Draw Mana's terrain-on-draw). The named carrier must be
        // real: an engine literal (Draw Mana, an aliased talent) — a typo'd carrier is the same
        // silent failure this pass exists to kill.
        const via = prose.match(/ENGINE-NATIVE VIA ([^:<]+):/i);
        if (via) {
          if (inEngineCode(via[1].trim())) continue;
          err(`data/adversaries.json (${advName} / ${it.name}): ENGINE-NATIVE VIA "${via[1].trim()}" — that carrier isn't a quoted literal in register-skills.js (typo? unwired?)`);
          continue;
        }
        err(`data/adversaries.json (${advName} / ${it.name}): text names a trigger but the ability has no events, ` +
            `no engine name-wiring, and no "NO NAMEABLE HOOK: <reason>" line — wire it or justify it (Ben 07-16)`);
      }
    }
  } catch (e) { /* reported by the earlier adversaries.json pass */ }
}

// --- pass 6: cue triggers must be DISPATCHABLE (the 07-19 dead-wiring family) --
// Handler-type presence (pass 2) can't catch a gm-cue whose `trigger` value nothing sweeps:
// "attack-hit" passed every gate and would never fire at the table (the 07-19 Malcurr audit
// found six such rules, plus two shipped in the 07-19d fens bestiary). The dispatch truth is
// the engine's own edhaCueRules(<actor>, "<trigger>") call sites — extract them, and hold
// every gm-cue rule (adversaries + authored talents) to that vocabulary. Hit cues are a
// different SHAPE, not a trigger: event "edha-on-hit" (and they only fire when the owner
// actually deals damage — a to-hit-only grab has no hook at all; that's a NO NAMEABLE HOOK).
{
  const dispatched = new Set();
  for (const m of engine.matchAll(/edhaCueRules\([^,()]+,\s*"([a-z-]+)"\)/g)) dispatched.add(m[1]);
  if (!dispatched.size) err("pass 6: no edhaCueRules call sites found in register-skills.js — extraction regex rotted?");
  const checkRule = (where, ev) => {
    const h = ev?.handler || {};
    if (h.type !== "edha-gm-cue") return;
    const evName = ev?.event, trig = h.trigger || "damaged";
    if (evName === "edha-on-hit") {
      // The on-hit dispatch keys on the EVENT and ignores handler.trigger entirely (three shipped
      // heroic talents carry the authoring default "damaged" here and work fine) — nothing to lint.
    } else if (evName === "edha-apply-watch") {
      if (!dispatched.has(trig)) {
        err(`${where}: gm-cue trigger "${trig}" is never dispatched (engine sweeps: ${[...dispatched].sort().join(", ")}). ` +
            `A hit cue is event "edha-on-hit" + trigger "on-hit"; a miss or damage-less hit has NO hook — use a "NO NAMEABLE HOOK: <reason>" line instead`);
      }
    } else {
      err(`${where}: gm-cue rules ride event "edha-apply-watch" (or "edha-on-hit" for hit cues) — got "${evName}"`);
    }
  };
  // whenTargetFooled preconditions: the rider reads a belief ledger only a seeming source writes —
  // an item named "The Seeming" (phantom loop) or an edha-ambush-belief rule on the same actor.
  const checkFooled = (where, ev, siblingItems) => {
    if (!ev?.handler?.whenTargetFooled) return;
    const hasSource = (siblingItems || []).some((s) =>
      s?.name === "The Seeming" ||
      (Array.isArray(s?.events) && s.events.some((e) => e?.handler?.type === "edha-ambush-belief")));
    if (!hasSource) {
      err(`${where}: whenTargetFooled rider but this adversary has no seeming source — no item named ` +
          `"The Seeming" and no edha-ambush-belief rule; the ledger is never written, so the rider can never apply`);
    }
  };
  try {
    const advData = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, "data/adversaries.json"), "utf8"));
    for (const [advName, adv] of Object.entries(advData)) {
      if (advName.startsWith("_")) continue;
      for (const it of adv.items || []) {
        for (const [j, ev] of (Array.isArray(it?.events) ? it.events : []).entries()) {
          const where = `data/adversaries.json (${advName} / ${it.name}) events[${j}]`;
          checkRule(where, ev);
          checkFooled(where, ev, adv.items);
        }
      }
    }
  } catch (e) { /* reported by the earlier adversaries.json pass */ }
  for (const file of fs.readdirSync(AUTHORED_DIR).filter((f) => f.endsWith(".json")).sort()) {
    let doc;
    try { doc = JSON.parse(fs.readFileSync(path.join(AUTHORED_DIR, file), "utf8")); } catch (e) { continue; }
    for (const [name, t] of Object.entries(doc.talents || {})) {
      for (const [evId, ev] of Object.entries(t.events || {})) {
        checkRule(`data/authored/${file} (${name}) event ${evId}`, ev);
      }
    }
  }
}

// --- pass 4: no raw talent-type gates (the unreachable-case family, 07-16) -----
// The Seeming's engine case was dead code for two days because a `useItem` hook gated on
// `item.type !== "talent"` while adversary abilities are action-typed twins/bespoke items.
// Every talent-type comparison must go through `edhaIsTalent(...)`; a deliberately strict
// site (PC talent budget, ⟳ Sync, pack scans) carries a `type-strict` marker comment.
engine.split("\n").forEach((lineText, i) => {
  if (!/[?.]type\s*[!=]==\s*["']talent["']/.test(lineText)) return;
  if (lineText.includes("type-strict")) return;
  err(`register-skills.js:${i + 1}: raw talent-type comparison — use edhaIsTalent(...) so adversary ` +
      `abilities (action-typed, adversaryTalent-flagged) aren't silently excluded; if strictness is ` +
      `deliberate, add a "type-strict: <reason>" comment on the line`);
});

// --- pass 10: no raw i18n KEY may reach card text (the label family, 07-27f) ----
// `CONFIG.COSMERE.skills[id].label` / `.statuses[id].label` hold raw i18n KEYS, not display text.
// EDHA's OWN statuses carry plain English, so every card naming one read fine while every card
// naming a NATIVE skill or status printed the key — bench run 1 shipped
// "COSMERE.Status.Disoriented" in an apply-status card and it survived four more runs, because the
// symptom looks like one talent's typo rather than a shared-helper gap. Nine sites were live.
// Read a label through edhaConditionLabel / edhaSkillLabel (which localize AND guard against a
// localize miss). A site that localizes on the same line is exempt; the helpers themselves carry
// the `label-helper` marker.
engine.split("\n").forEach((lineText, i) => {
  const t = lineText.trim();
  if (t.startsWith("*") || t.startsWith("//") || t.startsWith("/*")) return;      // prose, incl. these notes
  if (!/(COSMERE\??\.\??(skills|statuses|conditions|attributes)\??\.?\[[^\]]*\]\??\.label|EDHA_STATUSES\??\.?\[[^\]]*\]\??\.label)/.test(lineText)) return;
  if (lineText.includes("game.i18n") || lineText.includes("label-helper")) return;
  err(`register-skills.js:${i + 1}: raw *.label read — CONFIG.COSMERE.{skills,statuses}[id].label is an ` +
      `i18n KEY ("COSMERE.Actor.Skill.Agility"), not display text. Use edhaSkillLabel(id) or ` +
      `edhaConditionLabel(id); if this line genuinely localizes itself, keep the game.i18n call on it`);
});

// --- pass 8: the `execute-macro` budget (Ben's 07-24p ruling, gate landed 07-24s) ---------------
//
// Ben overruled a flat ban on the system's native `execute-macro` handler, and was right to: a macro
// STRING is testable in a way a "the table resolves this by hand" card never is — a gate can parse
// it and reason about its size. So it is permitted on a shipped talent, GATED. What it must never
// become is the thing iron rule 2a forbids: a cross-actor subsystem living in a text field, i.e. a
// second engine in a string.
//
// This lands BEFORE the first consumer, deliberately (Ben, 07-24r: "a prerequisite, not a
// nice-to-have"). There are zero `execute-macro` rules in data/ today, so nothing is grandfathered
// and the first one written is checked on the way in.
//
// THE LIMITS, and why these numbers. Ben sketched "~15 lines" and left the final call here.
//   · 20 LOGICAL LINES (blank lines and comment-only lines don't count). 15 was the right order of
//     magnitude but too tight in practice for the guard-clause style used everywhere else in this
//     project — `if (!actor) return;` lines are cheap and make code MORE readable, and a limit that
//     punishes them pushes authors toward dense one-liners, which is the opposite of the goal.
//   · 1200 CHARACTERS as well, because a line limit alone is evaded by one long line and a
//     character limit alone is evaded by whitespace. Either bound alone is decorative.
// Both are about SIZE only. They are not a claim that a 20-line macro is a good idea; they are the
// point past which "put it in a handler" stops being a matter of taste.
{
  const MAX_LOGICAL_LINES = 20;
  const MAX_CHARS = 1200;
  // A macro body runs as an async function body in Foundry, so top-level `await` is legal there and
  // must not read as a syntax error here.
  const AsyncFunction = Object.getPrototypeOf(async function () {}).constructor;

  // FIELD SHAPE (corrected 2026-07-26). The system's real execute-macro schema is `inline`
  // (BOOLEAN), `uuid`, and `macro: { type, command }` — camelCase, the macro source living in
  // macro.command. The first version of this pass read `h.Inline` / `h.MacroType` / `h.UUID`,
  // which are the PascalCase i18n LABEL keys from lang/en.json, not schema fields: it would have
  // false-failed every valid inline macro ("empty Inline body") and waved a UUID macro through.
  // Zero consumers existed, so nothing broke — but the gate was aimed at fields that don't exist.
  const checkMacro = (where, h) => {
    // A macro pointed at by UUID lives in the WORLD, not the repo: this gate cannot read it, a
    // reviewer cannot diff it, and a pack rebuild cannot carry it. That defeats the whole point of
    // moving behaviour onto the talent, so inline is the only permitted form.
    if (h.uuid || h.inline !== true) {
      err(`${where}: execute-macro must be INLINE (inline: true + macro.command, no uuid). A macro ` +
          `referenced by UUID lives in the world, not in data/ — this gate cannot parse it, a ` +
          `review cannot diff it, and a pack rebuild cannot carry it, so the behaviour is no more ` +
          `visible than the engine branch it replaced`);
    }
    const mtype = h.macro?.type;
    if (mtype && mtype !== "script") {
      err(`${where}: execute-macro macro.type "${mtype}" — only "script" is permitted; a chat ` +
          `macro as a rule payload is a card pretending to be automation`);
    }
    const body = String(h.macro?.command ?? "");
    if (!body.trim()) {
      err(`${where}: execute-macro has an empty macro.command — an empty macro is a talent that does nothing`);
      return;
    }
    if (body.length > MAX_CHARS) {
      err(`${where}: execute-macro macro.command is ${body.length} chars (max ${MAX_CHARS}) — if it ` +
          `needs to be this big it needs to be a handler; see iron rule 2a`);
    }
    const logical = body.split("\n")
      .map((l) => l.trim())
      .filter((l) => l && !l.startsWith("//") && !l.startsWith("*") && !l.startsWith("/*")).length;
    if (logical > MAX_LOGICAL_LINES) {
      err(`${where}: execute-macro macro.command is ${logical} logical lines (max ${MAX_LOGICAL_LINES}; ` +
          `blanks and comments are free) — if it needs to be this big it needs to be a handler`);
    }
    // A parse error means the rule is dead at the table and nothing says so. This is the check that
    // makes a macro defensible at all: it is the thing a manual card can never be given.
    try { new AsyncFunction(body); }
    catch (e) { err(`${where}: execute-macro macro.command does not parse — ${e.message}`); }
    // Size is the wrong thing to worry about on its own. A macro that registers a hook is a SECOND
    // ENGINE regardless of length: it outlives the use that created it, it re-registers on every
    // execution, and nothing ever removes it. Same for a timer.
    if (/\bHooks\s*\.\s*(on|once)\s*\(/.test(body)) {
      err(`${where}: execute-macro macro.command registers a Foundry hook. A hook outlives the use ` +
          `that created it and re-registers every time the macro runs, with nothing to remove it — ` +
          `that is a second engine in a text field whatever its length. Put it in register-skills.js`);
    }
    if (/\bset(Interval|Timeout)\s*\(/.test(body)) {
      err(`${where}: execute-macro macro.command schedules a timer — same problem as a hook: it ` +
          `outlives the use, and nothing cancels it. Put it in register-skills.js`);
    }
  };

  for (const file of fs.readdirSync(AUTHORED_DIR).filter((f) => f.endsWith(".json")).sort()) {
    let doc;
    try { doc = JSON.parse(fs.readFileSync(path.join(AUTHORED_DIR, file), "utf8")); } catch (e) { continue; }
    for (const [name, t] of Object.entries(doc.talents || {})) {
      for (const [evId, ev] of Object.entries(t.events || {})) {
        if (ev?.handler?.type === "execute-macro") checkMacro(`data/authored/${file} (${name}) event ${evId}`, ev.handler);
      }
    }
  }
  try {
    const advData = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, "data/adversaries.json"), "utf8"));
    for (const [advName, adv] of Object.entries(advData)) {
      if (advName.startsWith("_")) continue;
      for (const it of adv.items || []) {
        for (const [j, ev] of (Array.isArray(it?.events) ? it.events : []).entries()) {
          if (ev?.handler?.type === "execute-macro") checkMacro(`data/adversaries.json (${advName} / ${it.name}) events[${j}]`, ev.handler);
        }
      }
    }
  } catch (e) { /* pass 5 already reports a malformed adversaries.json */ }
}

// --- pass 7: the iron-rule-2b RATCHET (2026-07-24) -----------------------------
// Rule 2b: a talent's behaviour belongs on the talent (system.events / effects), not bound to
// its NAME in engine code. A name-keyed talent ships with empty Events/Effects tabs, editing
// them in Foundry does nothing, and renaming it silently unwires it — which is how 200 of 365
// talents came to violate a requirement that no rule had ever been written down to protect.
//
// The 221 talent names the engine mentioned in CODE on 2026-07-24 are frozen in
// scripts/name-keyed-allowlist.json. This pass makes that list a RATCHET: it may shrink, never
// grow. Comments are stripped first, deliberately — the engine's tree-section headers list
// talents by name on purpose (that IS the iron-rule-3 ledger) and must not read as violations.
{
  const ALLOW_PATH = path.join(__dirname, "name-keyed-allowlist.json");
  let allow;
  try { allow = JSON.parse(fs.readFileSync(ALLOW_PATH, "utf8")); }
  catch (e) { err(`pass 7: cannot read scripts/name-keyed-allowlist.json — ${e.message}`); allow = null; }

  if (allow) {
    // Only executable code is scanned — the shared stripComments (also pass 5's exemption).
    const stripped = engineCode.split("\n");

    const listed = new Set(allow.talents || []);
    const found = new Map();   // talent name -> first code line
    stripped.forEach((l, i) => {
      for (const m of l.matchAll(/"([^"\\\n]{3,45})"/g)) {
        if (!treeTalentNames.has(m[1]) || found.has(m[1])) continue;
        /* A `label:` value is a DISPLAY string, never dispatch (07-24u). The status-effect table
         * carries `covenant: { label: "Covenant", … }`, and rule 2b's actual test — "would renaming
         * the talent silently unwire it?" — is NO: the talent's rule references the status ID
         * (`status: "covenant"`, authored data), so a rename leaves a cosmetically stale label and
         * nothing more. Counting it kept Covenant on the ratchet after it had fully converted, which
         * makes the ratchet number FICTION in the safe-looking direction.
         *
         * Deliberately narrow. Measured before landing: this excludes exactly ONE name today
         * (Covenant, register-skills.js:178) and no other talent name in the engine occurs solely as
         * a label. Handler-schema labels are prose and never bare talent names. This is the FOURTH
         * gate the migration has had to teach a new form (audit §9n: audit.py's soft-laziness check,
         * lint pass 5, audit.py's locale codec) — treat the next one as a finding too. */
        if (/label:\s*$/.test(l.slice(0, m.index))) continue;
        found.set(m[1], i + 1);
      }
    });

    const added = [...found.keys()].filter((n) => !listed.has(n)).sort();
    for (const n of added) {
      err(`register-skills.js:${found.get(n)}: IRON RULE 2b — new name-keyed dispatch on "${n}". ` +
          `Behaviour must live on the talent (system.events / effects in data/authored/), not be ` +
          `bound to its name: a name-keyed talent shows EMPTY Events/Effects tabs in Foundry, ` +
          `editing them does nothing, and renaming it silently unwires it. If the mechanic ` +
          `genuinely cannot be a rule, take the declared ENGINE-OWNED exit (cue rule on the talent ` +
          `+ an "ENGINE_OWNED: <reason>" line in the tree-section header) — an exit still keeps the ` +
          `name out of engine code. The allowlist may SHRINK, never grow; do not add "${n}" to it.`);
    }

    const stale = [...listed].filter((n) => !found.has(n)).sort();
    if (stale.length) {
      err(`pass 7: ${stale.length} talent(s) migrated off name-keyed dispatch but still listed in ` +
          `scripts/name-keyed-allowlist.json — delete them so the ratchet reflects reality ` +
          `(${allow.originalCount} at 2026-07-24, ${found.size} now): ${stale.join(", ")}`);
    }
  }
}

// --- pass 9: handler FIELD names must match the registered schema (2026-07-26) --
// Pass 2 checks handler TYPES; nothing checked the field names INSIDE a handler object until the
// pre-deploy audit of the finished 2b migration. Foundry's DataModel silently DROPS any key the
// registered config schema doesn't define: the rule loads, the Events tab renders, and the
// mechanic just never fires — the field-level twin of the failure mode pass 2 kills. 221 talents
// were hand-authored across 27 sessions, so this must be a gate, not a one-off sweep.
// edha-* schemas are parsed from the engine's own registerItemEventHandlerType calls
// (scripts/handler-schemas.js — hard-fails if the parse rots); native schemas come from
// native-vocabulary.json's schemaFields. Rule-level keys are held to the system's rule schema
// too ({id, description, order, event, handler}) — a typo'd "hander" is a dead rule the same way.
{
  let handlerSchemas = null;
  try { handlerSchemas = parseHandlerSchemas(engine); }
  catch (e) { err(`pass 9: cannot parse engine handler schemas — ${e.message}`); }

  const AUTHORED_RULE_KEYS = new Set(["id", "description", "order", "event", "handler"]);
  // foundry-build's simplified adversary form carries ONLY these; anything else (an `order`, an
  // `id`) is silently discarded by the build — the same dropped-on-the-floor failure, one stage
  // earlier in the pipeline.
  const ADVERSARY_RULE_KEYS = new Set(["event", "handler", "description"]);

  const checkFields = (where, h) => {
    if (!handlerSchemas || !h || typeof h.type !== "string" || !h.type) return;
    let fields;
    if (h.type.startsWith("edha-")) {
      if (!handlerSchemas.has(h.type)) {
        err(`${where}: handler type "${h.type}" is never REGISTERED via registerItemEventHandlerType — ` +
            `pass 2's quoted-literal check can be satisfied by a comment or a dispatch string; a ` +
            `registration cannot. The rule is dead at the table.`);
        return;
      }
      fields = handlerSchemas.get(h.type);
    } else if (NATIVE_SCHEMA_FIELDS && NATIVE_SCHEMA_FIELDS.has(h.type)) {
      fields = NATIVE_SCHEMA_FIELDS.get(h.type);
    } else return; // unknown native type is pass 2's report, not ours
    for (const k of Object.keys(h)) {
      if (k === "type" || fields.has(k)) continue;
      err(`${where}: handler "${h.type}" has no field "${k}" — Foundry's DataModel silently drops ` +
          `unknown keys, so the rule loads, the tab looks right, and this key does NOTHING. ` +
          `Registered fields: ${[...fields].sort().join(", ")}`);
    }
  };

  for (const file of fs.readdirSync(AUTHORED_DIR).filter((f) => f.endsWith(".json")).sort()) {
    let doc;
    try { doc = JSON.parse(fs.readFileSync(path.join(AUTHORED_DIR, file), "utf8")); } catch (e) { continue; }
    for (const [name, t] of Object.entries(doc.talents || {})) {
      for (const [evId, ev] of Object.entries(t.events || {})) {
        const where = `data/authored/${file} (${name}) event ${evId}`;
        for (const k of Object.keys(ev || {})) {
          if (!AUTHORED_RULE_KEYS.has(k)) {
            err(`${where}: rule key "${k}" is not in the system's rule schema ` +
                `[${[...AUTHORED_RULE_KEYS].join(", ")}] — it is silently dropped`);
          }
        }
        checkFields(where, ev?.handler);
      }
    }
  }
  try {
    const advData = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, "data/adversaries.json"), "utf8"));
    for (const [advName, adv] of Object.entries(advData)) {
      if (advName.startsWith("_")) continue;
      for (const it of adv.items || []) {
        for (const [j, ev] of (Array.isArray(it?.events) ? it.events : []).entries()) {
          const where = `data/adversaries.json (${advName} / ${it.name}) events[${j}]`;
          for (const k of Object.keys(ev || {})) {
            if (!ADVERSARY_RULE_KEYS.has(k)) {
              err(`${where}: rule key "${k}" is not in the simplified adversary form ` +
                  `[${[...ADVERSARY_RULE_KEYS].join(", ")}] — foundry-build discards it`);
            }
          }
          checkFields(where, ev?.handler);
        }
      }
    }
  } catch (e) { /* reported by the earlier adversaries.json pass */ }
}

/* --- pass 11: no DEAD `system.<field>` path (the dead-field family, 07-27h) ---------------------
 *
 * THREE bugs, one shape, and each one cost a bench run to find:
 *   · 07-26l  `edhaAttackKind` read `item.system.range` — a weapon's range is `system.attack.range`,
 *             so EVERY melee/ranged gate in the engine was inert.
 *   · 07-26m  `edhaIsConstruct` read `actor.system.customType` — creature type is `system.type
 *             {id, custom}`, so Fault Line's Constructs ×3 could never fire.
 *   · 07-27g  the whole counter economy read/wrote `effect.system.count` — ActiveEffectDataModel has
 *             exactly {isStackable, stacks}, so every Insight read was 0 and NINE Knowledge
 *             behaviours degraded silently (six checklist rows went PARTIAL before it was caught).
 *
 * Why nothing caught them. Foundry's SchemaField DELETES unrecognised keys: `update({"system.count":
 * 3})` RESOLVES, stores nothing, and reads back undefined. There is no error, no warning, no rejected
 * promise. Unit tests do not help either — a test that stubs `{system: {count: 3}}` proves only that
 * the engine agrees with itself, which is exactly what tests/counter.test.js did for a year.
 *
 * So the check has to be against the SYSTEM's real schemas: `systemSchemaTopLevelFields` in
 * data/native-vocabulary.json (dumped from Ben's install by scripts/dump-native-vocabulary.js) is the
 * union of every top-level field name any cosmere DataModel declares. Engine-owned RegionBehavior
 * schemas are parsed live out of the engine itself, so a new behaviour field needs no allowlisting.
 *
 * LIMITS, stated so a green pass is not over-read:
 *   · It is a UNION across document types — a field real on a weapon but read off an actor PASSES.
 *     "Not obviously dead", never "correct for this document".
 *   · TOP-LEVEL heads only. `system.attack.range` is fine and `system.range` is not, which is the
 *     distinction the 07-26l bug turned on; a wrong SECOND segment is still invisible here.
 *   · Skipped when the snapshot predates the field list (warn, don't guess). */
{
  const SNAP = path.join(REPO_ROOT, "data", "native-vocabulary.json");
  let known = null;
  try {
    const v = JSON.parse(fs.readFileSync(SNAP, "utf8"));
    if (Array.isArray(v.systemSchemaTopLevelFields) && v.systemSchemaTopLevelFields.length >= 50) {
      known = new Set(v.systemSchemaTopLevelFields);
    } else {
      console.warn("⚠ lint-refs pass 11: native-vocabulary.json has no systemSchemaTopLevelFields — dead-field checking SKIPPED. Regenerate with: node scripts/dump-native-vocabulary.js");
    }
  } catch (e) { /* pass 2's block already warned about an unreadable snapshot */ }

  if (known) {
    // Fields the ENGINE itself declares on its own RegionBehavior DataModels — real `system.*` paths
    // on documents the cosmere system knows nothing about. Parsed, not allowlisted, so adding a
    // behaviour field never means editing this linter.
    for (const m of engine.matchAll(/defineSchema\s*\(\s*\)\s*\{/g)) {
      const open = m.index + m[0].length - 1;
      let close; try { close = matchBrace(engine, open); } catch (e) { continue; }
      const body = engine.slice(open, close + 1);
      for (const r of body.matchAll(/return\s*\{/g)) {
        const o = open + r.index + r[0].length - 1;
        try { for (const k of topLevelKeys(engine.slice(o + 1, matchBrace(engine, o)))) known.add(k); }
        catch (e) { /* skip an unparsable literal */ }
      }
    }
    // Inherited from CORE Foundry region-behavior types the engine subclasses or configures.
    // Explicit because they come from foundry.mjs, which this repo cannot read.
    for (const k of ["difficulties", "terrainTypes"]) known.add(k);   // ModifyMovementCostRegionBehaviorType

    // Every place the repo touches a cosmere document's `system` data.
    const SCANNED = [
      ["module-src/scripts/register-skills.js", engine],
      ...["scripts/foundry-build.js", "scripts/foundry-build-parts.js", "scripts/edha-pack-io.js",
          "scripts/bench-setup-console.js", "scripts/playtest-setup-console.js"]
        .map((f) => [f, fs.existsSync(path.join(REPO_ROOT, f)) ? fs.readFileSync(path.join(REPO_ROOT, f), "utf8") : null])
        .filter(([, src]) => src !== null),
    ];
    const DEAD = (file, line, head, how) =>
      err(`${file}:${line}: \`system.${head}\` — no cosmere DataModel declares a top-level "${head}" ` +
          `field, so this ${how} is DEAD: Foundry's SchemaField deletes unrecognised keys, the write ` +
          `resolves without error and stores nothing, and every read is undefined. Check the real ` +
          `schema (data/native-vocabulary.json systemSchemaTopLevelFields) before assuming a field ` +
          `exists — three shipped bugs came from guessing one`);

    for (const [file, src] of SCANNED) {
      const blanked = blankStringsAndComments(src);   // offsets preserved; prose can't false-match
      // Comments blanked but STRING BODIES kept — form (b) below has to look inside strings, and the
      // engine's own comments quote `system.count` / `system.range` when explaining these very bugs.
      const noComments = blankStringsAndComments(src, { keepStrings: true });
      const lineAt = (idx) => src.slice(0, idx).split("\n").length;

      // (a) property access — `system.foo`, `system?.foo`. No whitespace after the dot, so the word
      //     "system." at the end of a sentence cannot match. `game.system.*` is the SYSTEM object.
      for (const m of blanked.matchAll(/\bsystem(?:\?\.|\.)([A-Za-z_$][\w$]*)/g)) {
        if (/game\s*\??\.\s*$/.test(blanked.slice(Math.max(0, m.index - 12), m.index))) continue;
        if (!known.has(m[1])) DEAD(file, lineAt(m.index), m[1], "read");
      }
      // (b) flat update paths — `update({"system.foo": v})`, `getProperty(d, "system.foo")`. These
      //     live INSIDE strings, so they are read from the comments-only-blanked copy.
      for (const m of noComments.matchAll(/["'`]system\.([A-Za-z_$][\w$]*)/g)) {
        if (!known.has(m[1])) DEAD(file, lineAt(m.index), m[1], "write path");
      }
      // (c) creation/update object literals — `system: { foo: … }`. This is the form the 07-27h status
      //     registration used, and neither (a) nor (b) can see it.
      for (const m of blanked.matchAll(/(?:^|[^\w$.])system\s*:\s*\{/g)) {
        const open = src.indexOf("{", m.index);
        let close; try { close = matchBrace(src, open); } catch (e) { continue; }
        let keys; try { keys = topLevelKeys(src.slice(open + 1, close)); } catch (e) { continue; }
        for (const k of keys) if (!known.has(k)) DEAD(file, lineAt(m.index), k, "stored key");
      }
    }
  }
}

/* --- pass 12: no DEAD content-vocabulary id in authored data (the dead-ID family, 07-27j) -------
 *
 * Pass 11 gates dead `system.<field>` paths in the ENGINE. This is the same disease one layer
 * over, in the DATA: an authored rule naming a cosmere id that does not exist.
 *
 * Bench run 9 found EIGHT talents wired to skill ids the system never defined — `itm` for
 * Intimidation (really `inm`), `per` for Perception/Persuasion (`prc`/`prs`), `ldr` for
 * Leadership (`lea`) — and every failure was SILENT, because nothing in this stack validates an
 * id against a vocabulary:
 *   · a contest `skill` is compared to the id the player ACTUALLY rolled, so a dead id never
 *     matches and the contest waits for a roll that can never come. Sharp Eye and Set at Odds
 *     were total no-ops; Synchronized Assault charged 2 focus and did nothing.
 *   · `@skills.<id>.rank` substitutes to 0 when the id is absent from rollData, so Feinting
 *     Strike drained "0" focus at Intimidation 3 and Rallying Shout printed "+ 0 health".
 *   · a `whenSkill` rider simply never fires. Flamestance never worked in its whole life, with
 *     Ironstance (`ins`, valid) as the working control sitting right beside it.
 *
 * The vocabulary is two halves, and BOTH must be counted or the gate flags correct data:
 *   · the SYSTEM's ids — `contentVocabulary` in data/native-vocabulary.json, dumped from Ben's
 *     install by scripts/dump-native-vocabulary.js.
 *   · EDHA's OWN additions — five leyline SKILLS (`LEYLINE_SKILLS`) and ~30 STATUSES
 *     (`EDHA_STATUSES`), parsed LIVE out of the engine here, so registering a new one never
 *     means editing this linter or re-dumping a snapshot.
 *
 * TWO exemptions, both real semantics rather than convenience — a linter that flags correct data
 * gets disabled, which is worse than no linter:
 *   · `edha-watch {watch: "die-step"}` reads `whenSkill` as the die-step ENTRY KEY, not a skill.
 *     Sovereign's Favor's `exalt` is correct and documented in the handler's own field hint.
 *   · a contest skill field may hold an ATTRIBUTE id. Several cards call for an attribute test
 *     ("each character tests Speed vs. your Red") and `spd` is the engine's own default in
 *     `edhaFoeSkillVsColor`. `@skills.<id>` is NOT given that latitude: rollData keys `skills`
 *     off CONFIG.COSMERE.skills alone, so `@skills.spd.rank` really is dead — `@attr.spd` is the
 *     attribute form, and this pass checks that separately.
 *
 * LIMITS, stated so a green pass is not over-read: it checks ids against vocabularies, never
 * whether the id is the RIGHT one for the card — `prc` where the prose says Persuasion passes
 * here and is still wrong. Only the fields listed below are checked; a new handler that invents
 * another id-bearing field name needs a line adding. */
{
  const SNAP = path.join(REPO_ROOT, "data", "native-vocabulary.json");
  let vocab = null;
  try {
    const v = JSON.parse(fs.readFileSync(SNAP, "utf8"));
    if (v.contentVocabulary?.skills?.length >= 18 && v.contentVocabulary?.statuses?.length >= 15) vocab = v.contentVocabulary;
    else console.warn("⚠ lint-refs pass 12: native-vocabulary.json has no contentVocabulary — authored id checking SKIPPED. Regenerate with: node scripts/dump-native-vocabulary.js");
  } catch (e) { /* pass 2's block already warned about an unreadable snapshot */ }

  if (vocab) {
    /* EDHA's own registrations, parsed out of the engine (never allowlisted — see the header).
     * NOT `topLevelKeys`: that helper consumes a quoted key as a string LITERAL and never records
     * it, so `"tagged": {…}` in EDHA_STATUSES came back missing and the gate flagged Tagging Shot
     * — a correct talent — on its first run. Both key forms are read here. (The same blind spot
     * exists in topLevelKeys for pass 11's schema harvesting, where it can only ever ADD a false
     * positive, never hide a real one; left alone deliberately rather than changing a parser three
     * passes depend on. Recorded in the 07-27j delta.) */
    const engineKeys = (constName) => {
      const m = engine.match(new RegExp(`const ${constName} = \\{`));
      if (!m) return [];
      const open = m.index + m[0].length - 1;
      let body; try { body = engine.slice(open + 1, matchBrace(engine, open)); } catch (e) { return []; }
      const keys = new Set();
      let depth = 0;
      for (let i = 0; i < body.length; i++) {
        const c = body[i];
        if (c === "/" && body[i + 1] === "/") { while (i < body.length && body[i] !== "\n") i++; continue; }
        if (c === "/" && body[i + 1] === "*") { const e = body.indexOf("*/", i + 2); if (e < 0) break; i = e + 1; continue; }
        if (c === "{" || c === "(" || c === "[") { depth++; continue; }
        if (c === "}" || c === ")" || c === "]") { depth--; continue; }
        if (depth !== 0) { if (c === '"' || c === "'" || c === "`") { for (i++; i < body.length; i++) { if (body[i] === "\\") { i++; continue; } if (body[i] === c) break; } } continue; }
        // depth 0: a key is either `bare:` or `"quoted":`
        if (c === '"' || c === "'") {
          const q = c; let j = i + 1, s = "";
          for (; j < body.length; j++) { if (body[j] === "\\") { s += body[++j]; continue; } if (body[j] === q) break; s += body[j]; }
          let k = j + 1; while (k < body.length && /\s/.test(body[k])) k++;
          if (body[k] === ":") keys.add(s);
          i = j;
        } else if (/[A-Za-z_$]/.test(c)) {
          let j = i + 1; while (j < body.length && /[\w$]/.test(body[j])) j++;
          let k = j; while (k < body.length && /\s/.test(body[k])) k++;
          if (body[k] === ":") keys.add(body.slice(i, j));
          i = j - 1;
        }
      }
      return [...keys];
    };
    const leylineSkills = engineKeys("LEYLINE_SKILLS");
    const edhaStatuses = engineKeys("EDHA_STATUSES");
    if (leylineSkills.length !== 5) err(`lint-refs pass 12: parsed ${leylineSkills.length} LEYLINE_SKILLS out of the engine (expected 5) — the extraction rotted; fix it before trusting this pass`);
    if (edhaStatuses.length < 20) err(`lint-refs pass 12: parsed ${edhaStatuses.length} EDHA_STATUSES out of the engine (expected ≥ 20) — the extraction rotted; fix it before trusting this pass`);

    const SKILLS = new Set([...vocab.skills, ...leylineSkills]);          // valid in @skills.<id>
    const ATTRS = new Set(vocab.attributes);
    const CONTEST = new Set([...SKILLS, ...ATTRS]);                        // valid in a contest skill field
    const STATUSES = new Set([...vocab.statuses, ...edhaStatuses]);
    const DAMAGE = new Set(vocab.damageTypes);
    const DEFENSES = new Set(vocab.attributeGroups);

    // field name -> [vocabulary, set, extra literals that are legal non-ids]
    const FIELDS = {
      skill: ["skill or attribute", CONTEST, []],
      whenSkill: ["skill or attribute", CONTEST, []],
      riderSkill: ["skill or attribute", CONTEST, []],
      saveSkill: ["skill or attribute", CONTEST, []],
      targetSkill: ["skill or attribute", CONTEST, []],
      status: ["status", STATUSES, []],
      failStatus: ["status", STATUSES, []],
      requireSelfStatus: ["status", STATUSES, []],
      requireTargetStatus: ["status", STATUSES, []],
      whenTargetStatus: ["status", STATUSES, []],
      damageType: ["damage type", DAMAGE, []],
      whenDamageType: ["damage type", DAMAGE, ["any"]],
      def: ["defense", DEFENSES, []],
    };

    const idErr = (where, field, id, kind, set) =>
      err(`${where}: ${field} "${id}" is not a valid cosmere ${kind} — nothing matches it, so the rule is ` +
          `SILENTLY inert (a contest waits for a roll that never comes; an @skills ref substitutes to 0). ` +
          `Valid: ${[...set].sort().join(" ")}`);

    for (const file of fs.readdirSync(AUTHORED_DIR).filter((f) => f.endsWith(".json")).sort()) {
      let doc;
      try { doc = JSON.parse(fs.readFileSync(path.join(AUTHORED_DIR, file), "utf8")); } catch (e) { continue; }
      for (const [name, t] of Object.entries(doc.talents || {})) {
        const base = `data/authored/${file} (${name})`;

        // (a) handler id FIELDS. Values may be comma-lists; every member must resolve.
        for (const [evId, ev] of Object.entries(t.events || {})) {
          const h = ev?.handler; if (!h || typeof h !== "object") continue;
          for (const [field, [kind, set, extra]] of Object.entries(FIELDS)) {
            const raw = h[field];
            if (typeof raw !== "string" || !raw.trim()) continue;
            // `edha-watch {watch: "die-step"}` reads whenSkill as the ENTRY KEY, not a skill.
            if (field === "whenSkill" && h.type === "edha-watch" && h.watch === "die-step") continue;
            for (const id of raw.split(",").map((s) => s.trim()).filter(Boolean)) {
              if (!set.has(id) && !extra.includes(id)) idErr(`${base} event ${evId}`, field, id, kind, set);
            }
          }
        }

        // (b) @skills.<id> / @attr.<id> substitutions in ANY authored string (formulas, note text,
        //     descriptions). This is the half that printed "0" rather than doing nothing.
        const walk = (node, trail) => {
          if (Array.isArray(node)) return node.forEach((v, i) => walk(v, `${trail}[${i}]`));
          if (node && typeof node === "object") { for (const [k, v] of Object.entries(node)) walk(v, trail ? `${trail}.${k}` : k); return; }
          if (typeof node !== "string") return;
          for (const m of node.matchAll(/@skills\.([A-Za-z_]\w*)/g)) {
            if (!SKILLS.has(m[1])) idErr(`${base} ${trail}`, "@skills ref", m[1], ATTRS.has(m[1]) ? "skill (it is an ATTRIBUTE — use @attr." + m[1] + ")" : "skill", SKILLS);
          }
          for (const m of node.matchAll(/@attr\.([A-Za-z_]\w*)/g)) {
            if (!ATTRS.has(m[1])) idErr(`${base} ${trail}`, "@attr ref", m[1], "attribute", ATTRS);
          }
        };
        walk(t, "");
      }
    }
  }
}

/* --- pass 13: authored ENUM values that reach a SYSTEM channel (the wrong-shape family, 07-27l) --
 *
 * Passes 11 and 12 gate dead NAMES — a `system.<field>` the schema never declares, a cosmere id the
 * vocabulary never had. This is the third member of the same disease: a name that resolves fine but
 * whose VALUE is the wrong shape for the channel it is written into.
 *
 * The instance. `AdvantageMode` in the cosmere system is a STRING enum (index.js L262-267:
 * none|advantage|disadvantage) and `D20Roll.hasAdvantage` is an `===` against it. Bench run 10 found
 * `edhaQuarryAdvPreRoll` writing the NUMBER 1, so `configureModifiers()` fell through to
 * `d20.number = 1` and every attack on a marked quarry rolled a plain 1d20 — silently, for the
 * mechanic's whole life, with the wrong value still readable on the roll object so a console probe
 * reported "advantage is set". The retired `edhaStanceAdvPreRoll` had made the same mistake.
 *
 * What THIS pass gates is the DATA half, which nothing covered. `edha-test-rider` takes the authored
 * `mode` straight off the rule and assigns it to `roll.options.advantageMode` with no narrowing —
 * so `mode: "adv"` on a talent is byte-for-byte the same bug, reachable by anyone editing the
 * Events tab in Foundry, and it would pass every other gate. (`edha-next-test-mod` normalises
 * anything non-"advantage" to disadvantage, which is worse, not better: a typo silently INVERTS
 * the rule. Both are checked.)
 *
 * The ENGINE half is deliberately NOT duplicated here — `tests/advantage-channel.test.js` owns it,
 * scanning every `.advantageMode =` site for the string value AND the configureDialog wrapper, with
 * a mutation check against this very defect. Two gates for one check would just be two things to
 * keep in sync; the split follows pass 11 / dead-field.test.js.
 *
 * EXTENDING IT: add `<handler type>: { <field>: [legal values] }` below. Only closed sets belong
 * here — a field whose legal values are open-ended is a doc problem, not a lint one. `mode` on
 * other handlers (edha-marker-command, edha-summon-effect, edha-owner-list, edha-snare-react,
 * edha-place-hazard) means entirely different things and is intentionally absent. */
{
  const ENUM_FIELDS = {
    "edha-test-rider": {
      mode: { legal: ["advantage", "disadvantage"],
              why: "it is assigned straight to roll.options.advantageMode; any other string reads as NO advantage and the roll silently stays 1d20" },
    },
    "edha-next-test-mod": {
      mode: { legal: ["advantage", "disadvantage"],
              why: "the engine narrows anything that is not exactly \"advantage\" to DISADVANTAGE — a typo does not fail, it inverts the rule" },
    },
  };

  const checkEnums = (where, h) => {
    const spec = h && typeof h === "object" ? ENUM_FIELDS[h.type] : null;
    if (!spec) return;
    for (const [field, { legal, why }] of Object.entries(spec)) {
      const v = h[field];
      if (v === undefined || v === null || v === "") continue;   // absent is legal — these are optional fields
      if (typeof v !== "string" || !legal.includes(v)) {
        err(`${where}: ${h.type} field "${field}" is ${JSON.stringify(v)} — it must be one of ` +
            `[${legal.join(", ")}], because ${why}`);
      }
    }
  };

  for (const file of fs.readdirSync(AUTHORED_DIR).filter((f) => f.endsWith(".json")).sort()) {
    let doc;
    try { doc = JSON.parse(fs.readFileSync(path.join(AUTHORED_DIR, file), "utf8")); } catch (e) { continue; }
    for (const [name, t] of Object.entries(doc.talents || {})) {
      for (const [evId, ev] of Object.entries(t.events || {})) {
        checkEnums(`data/authored/${file} (${name}) event ${evId}`, ev?.handler);
      }
    }
  }
  try {
    const advData = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, "data/adversaries.json"), "utf8"));
    for (const [advName, adv] of Object.entries(advData)) {
      if (advName.startsWith("_")) continue;
      for (const it of adv.items || []) {
        for (const [j, ev] of (Array.isArray(it?.events) ? it.events : []).entries()) {
          checkEnums(`data/adversaries.json (${advName} / ${it.name}) events[${j}]`, ev?.handler);
        }
      }
    }
  } catch (e) { /* reported by the earlier adversaries.json pass */ }
}

/* --- pass 14: a gated test must be able to ROLL (the mute-def-test family, 07-26j + 07-27n) ------
 *
 * H1 `edha-def-test` is a DECIDER, not a roller. Its executor calls `edhaQueueContest(owner, skill,
 * cb)` and then waits for the owner's own d20 to arrive on `cosmere-rpg.{skill,attack,item}Roll`.
 * If no test is ever rolled, the queue entry simply expires after EDHA_CONTEST_TTL — no error, no
 * warning, no card. The talent is a total silent no-op.
 *
 * Whether a capturable d20 happens is decided entirely by the ITEM, in the system's own `use()`
 * (systems/cosmere-rpg/index.js ~L7188). `rollRequired` is
 * `activation.type === "skill_test" || hasDamage`, but the two arms are NOT interchangeable here:
 * only the skill_test arm calls `item.roll()` → `d20Roll` → `cosmere-rpg.itemRoll`, which is what
 * `edhaContestWatch` listens on. The damage arm calls `rollDamage()` → `damageRoll` →
 * `cosmere-rpg.damageRoll`, a DamageRoll on a hook the watcher does not subscribe to. So a damage
 * formula does NOT rescue a `utility` activation — `activation.type: "skill_test"` is the only
 * shape that can resolve a def-test, and that is exactly what this pass requires.
 *
 * And when the roll DOES happen, `edhaTryResolveContest` matches it by skill
 * (`if (q.color && r.skill && r.skill !== q.color) return;`) — so the item's own
 * `activation.skill` must be the SAME skill the rule names, or the contest waits forever for a roll
 * that already went past.
 *
 * TWO instances, on two different surfaces, which is why this is a gate and not a fix:
 *   · 2026-07-26j — SIX adversary abilities (Callthief Counterpoint, Surecat Redirect Momentum,
 *     Reeve-Owl Sovereign of Solitude, both Rootling Swarm abilities, Tussock-Sow Drive the Prey)
 *     were born mute because `advItemDoc` only promoted ATTACK items to skill_test. Fixed in the
 *     BUILDER — it now reads the skill off the def-test rule.
 *   · 2026-07-27n — Sharp Eye (Hunter), on the TALENT surface, which the builder fix never touched:
 *     an authored overlay wins verbatim, so its `utility` / no-skill activation shipped as authored
 *     and the talent did nothing for its whole life. Bench run 11 measured the null result twice.
 * Both surfaces are checked below so a third instance cannot land on either.
 *
 * THE ONE LEGAL EXEMPTION: owner-sweep mode with no test at all — `targetList` set AND `vs: "none"`
 * (Chaos's Unravel Everything). Read the executor: that combination returns from `sweep(null)`
 * before `edhaQueueContest` is ever reached, so no roll is needed. `vs: "none"` WITHOUT a
 * `targetList` is NOT exempt — it still falls through to the queue and still needs the roll. */
{
  const defTestOf = (rules) => {
    for (const r of rules) if (r?.handler?.type === "edha-def-test") return r.handler;
    return null;
  };
  // Owner-sweep with no test: returns before edhaQueueContest. The ONLY shape that needs no roll.
  const needsRoll = (h) => !(h.targetList && h.vs === "none");

  const checkRollable = (where, h, activation, { effectiveSkill = undefined } = {}) => {
    if (!h || !needsRoll(h)) return;
    const type = activation?.type;
    if (type !== "skill_test") {
      err(`${where}: carries an edha-def-test rule but activation.type is "${type ?? "(none)"}" — only a ` +
          `"skill_test" activation rolls the d20 the contest captures (a damage formula does NOT count: it ` +
          `fires damageRoll, which the watcher does not listen on). H1 queues a contest no roll can ever ` +
          `resolve, so the talent is a SILENT no-op — nothing spent, no card, no error. Set activation.type to ` +
          `"skill_test" and activation.skill to "${h.skill || "<the rule's skill>"}".`);
      return;
    }
    if (!h.skill) return;                      // no skill named on the rule → nothing to match against
    if (effectiveSkill === undefined) return;  // caller cannot determine it (see the adversary note)
    if (effectiveSkill !== h.skill) {
      err(`${where}: the item rolls "${effectiveSkill ?? "(no skill)"}" but its edha-def-test rule waits for ` +
          `"${h.skill}" — edhaTryResolveContest matches the captured roll BY SKILL, so the contest never resolves ` +
          `and the talent is a silent no-op. The two must name the same skill.`);
    }
  };

  for (const file of fs.readdirSync(AUTHORED_DIR).filter((f) => f.endsWith(".json")).sort()) {
    let doc;
    try { doc = JSON.parse(fs.readFileSync(path.join(AUTHORED_DIR, file), "utf8")); } catch (e) { continue; }
    for (const [name, t] of Object.entries(doc.talents || {})) {
      const h = defTestOf(Object.values(t.events || {}));
      if (!h) continue;
      checkRollable(`data/authored/${file} (${name})`, h, t.activation, {
        effectiveSkill: t.activation?.skill ?? null,
      });
    }
  }
  /* The adversary half. `advItemDoc` DERIVES the activation, so the authored JSON is `utility` by
   * design and only the derived skill is checkable here — mirrored from foundry-build.js
   * (`raw.skill || defTestSkill` for a non-attack, the weapon skill for an attack). The type check
   * is skipped for the same reason: the builder promotes it. Kept narrow deliberately — this is a
   * mirror of one builder line, not a re-implementation of the builder. */
  try {
    const advData = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, "data/adversaries.json"), "utf8"));
    for (const [advName, adv] of Object.entries(advData)) {
      if (advName.startsWith("_")) continue;
      for (const it of adv.items || []) {
        const h = defTestOf(Array.isArray(it?.events) ? it.events : []);
        if (!h || !needsRoll(h) || !h.skill) continue;
        const isAttack = it.attack != null;
        const ranged = /\brange\b/i.test(it.range || "");
        const effectiveSkill = isAttack ? (it.skill || (ranged ? "lwp" : "hwp")) : (it.skill || h.skill);
        if (effectiveSkill !== h.skill) {
          err(`data/adversaries.json (${advName} / ${it.name}): the ability rolls "${effectiveSkill}" but its ` +
              `edha-def-test rule waits for "${h.skill}" — the contest is matched BY SKILL, so it never resolves ` +
              `and the ability is a silent no-op. Align the ability's "skill" with the rule's.`);
        }
      }
    }
  } catch (e) { /* reported by the earlier adversaries.json pass */ }
}

/* --- pass 15: a hook that WRITES the world must not be gated on a raw isGM (the two-GM family) ---
 *
 * `updateActor`, `deleteToken`, `combatTurnChange` and friends fire on EVERY connected client. A
 * handler gated on `game.user.isGM` therefore runs once PER CONNECTED GM — and Ben's table runs
 * `Gamemaster` plus the agent-bench `Bench`, so "per GM" is two. Everything the handler does then
 * happens twice: the card posts twice, the Region is dropped twice, the actor is deleted twice
 * (which is a server-side "Actor does not exist" race, not a harmless no-op).
 *
 * This family has now bitten four times across two marathons — Apex Form's double injury (07-27b,
 * misdiagnosed first as a double MOMENT), the 2bW-13 sweep that moved ~70 sites onto
 * `edhaDefBuffGmGate()` in the same pass, and bench run 13's double-posted "dissipates" card, whose
 * own sweep found two more (a duplicated ignite Region, and the summon last-token actor delete).
 * Each time the FIX was one character of thought and the COST was a live table seeing double, so it
 * is gated rather than swept again.
 *
 * The rule: if a hook body references `isGM` and performs a world write, it must also carry the
 * one-applier gate (`edhaDefBuffGmGate()` — or a hand-written `activeGM` check, which several
 * older sites still use and which is equivalent).
 *
 * `render*` hooks are exempt, and that is not a loophole: injecting a button into a sidebar or a
 * sheet is PER-CLIENT work, and gating it to one GM would hide the button from every other GM.
 * Their `.update(`-shaped calls are canvas/DOM refreshes, not database writes.
 *
 * Delimitation: this engine registers every hook as a top-level statement (`Hooks.on(` at column 0),
 * so a body runs from that anchor until its parens balance again — counted on the STRING-BLANKED
 * copy, with escaped `\(`/`\)` (regex literals) neutralised first. The scan then asserts it
 * delimited a plausible number of hooks, so if the style ever changes the pass fails loudly instead
 * of silently checking nothing (the pass-12 "the extraction rotted" convention).
 */
{
  const codeLines = blankStringsAndComments(engine).split("\n");                        // strings blanked: no false hits from card HTML
  const nameLines = blankStringsAndComments(engine, { keepStrings: true }).split("\n"); // for the hook NAME only
  const parenDelta = (l) => {
    const s = l.replace(/\\[()]/g, "  ");
    return (s.split("(").length - 1) - (s.split(")").length - 1);
  };
  // A world write is a database write. Canvas/UI refreshes and in-memory Map/Set deletes are not.
  const RECEIVER_EXEMPT = new Set(["perception", "canvas", "ui", "app", "element", "sheet", "window"]);
  function worldWrite(body) {
    if (/ChatMessage\.create/.test(body)) return "ChatMessage.create";
    if (/(?:create|delete)EmbeddedDocuments\(/.test(body)) return "an embedded-document create/delete";
    if (/(?:create|delete)Documents\(/.test(body)) return "a document create/delete";
    if (/toggleStatusEffect\(/.test(body)) return "a status-effect toggle";
    if (/\.(?:setFlag|unsetFlag)\(/.test(body)) return "a flag write";
    if (/game\.settings\.set\(/.test(body)) return "a world-setting write";
    if (/\bedha[A-Za-z]*GM\(/.test(body)) return "a GM-side write helper";
    for (const m of body.matchAll(/([A-Za-z_$][\w$]*)\s*\??\.(update|delete)\(/g)) {
      if (RECEIVER_EXEMPT.has(m[1]) || /^[A-Z][A-Z0-9_]{2,}$/.test(m[1])) continue;     // canvas refresh / Map.delete
      return `a document ${m[2]}`;
    }
    return null;
  }
  let scanned = 0;
  for (let start = 0; start < codeLines.length; start++) {
    if (!/^Hooks\.(?:on|once)\(/.test(codeLines[start])) continue;
    let depth = 0, end = -1;
    for (let i = start; i < codeLines.length; i++) {
      depth += parenDelta(codeLines[i]);
      if (depth <= 0) { end = i; break; }
    }
    if (end < 0) {
      err(`lint-refs pass 15: could not delimit the hook registered at register-skills.js:${start + 1} — ` +
          `its parens never balance. Fix the scan before trusting this gate.`);
      continue;
    }
    scanned++;
    const body = codeLines.slice(start, end + 1).join("\n");
    const name = (nameLines[start].match(/^Hooks\.(?:on|once)\(\s*"([^"]*)"/) || [])[1] || "";
    if (name.startsWith("render")) continue;                              // per-client UI injection — see above
    if (!/\bisGM\b/.test(body)) continue;
    if (/activeGM|edhaDefBuffGmGate/.test(body)) continue;                // already one-applier
    const what = worldWrite(body);
    if (!what) continue;
    err(`register-skills.js:${start + 1} — the "${name}" hook is gated on a raw isGM but performs ${what}. ` +
        `That hook fires on every client, so EVERY connected GM runs it: Ben's table has two (Gamemaster + Bench), ` +
        `and the write happens twice — bench run 13 measured one "dissipates" card posted twice, 1 ms apart. ` +
        `Use edhaDefBuffGmGate() ("exactly one GM writes"), as ~70 sites already do.`);
  }
  if (scanned < 150) {
    err(`lint-refs pass 15: only ${scanned} top-level hook registrations were delimited (expected 150+) — ` +
        `the scan rotted; fix it before trusting this pass.`);
  }
}

/* --- pass 16: a hazard Region must declare its owner in the ONE vocabulary (the split-flag family) --
 *
 * Bench run 14 measured Combustion Chain unable to fire off a Pyre zone — the canonical Destruction
 * pairing — and the cause was not the talent, the rule, or the gate above it. It was that the engine
 * had grown TWO spellings for "who owns this dangerous terrain", one per placer:
 *
 *   edhaPlaceHazardRegionGM · the burst path · green terrain ->  terrain: { ownerUuid }   (nested)
 *   edhaPlaceHazard (the `edha-place-hazard` handler)         ->  sourceOwnerUuid          (flat)
 *
 * ...and TWO readers, each understanding only one. `edhaOwnedTerrainRegions` — the membership spine
 * behind `edhaTokenInOwnedTerrain` (which gates the ENTIRE `edha-zone-react {defeat-in-zone}` ignite
 * sweep), behind `edhaEnemiesInOwnedTerrain` (Apex Predator) and behind Pack Sense — read only the
 * nested one, so an entire family of Regions was invisible to every membership question in the
 * engine. Nothing failed loudly; the gate simply never opened, for the mechanic's whole life. Six
 * gates and 27 migration passes went past it because a written flag and a read flag both existed —
 * they just were not the same flag.
 *
 * The rule: any Region-create whose `edha-content` flags declare `hazard:` must also declare
 * `terrain: { ownerUuid: ... }`, and no Region-create may write a FLAT `*OwnerUuid` key beside it.
 * Nested namespaces (terrain / fortified / ...) are the vocabulary; a flat owner key is the bug.
 *
 * Delimitation follows pass 15: `createEmbeddedDocuments("Region", ...)` delimited by paren balance
 * on the string-blanked copy, then the flags literal read back out of the ORIGINAL text. The scan
 * asserts it found a plausible number of Region creates, so a style change fails loudly rather than
 * silently checking nothing (the pass-12 "the extraction rotted" convention).
 */
{
  const blanked = blankStringsAndComments(engine);          // offsets preserved — see the helper
  const parenDelta = (s) => {
    const t = s.replace(/\\[()]/g, "  ");
    return (t.split("(").length - 1) - (t.split(")").length - 1);
  };
  const lineOf = (idx) => engine.slice(0, idx).split("\n").length;
  let scanned = 0;
  const RE = /createEmbeddedDocuments\(\s*"Region"/g;
  // The literal is quoted, so find the anchors in the string-KEEPING copy, then balance on the blanked one.
  const withStrings = blankStringsAndComments(engine, { keepStrings: true });
  for (const m of withStrings.matchAll(RE)) {
    const open = withStrings.indexOf("(", m.index + "createEmbeddedDocuments".length);
    let depth = 0, end = -1;
    for (let i = open; i < blanked.length; i++) {
      const d = parenDelta(blanked[i]);
      depth += d;
      if (depth <= 0 && d !== 0) { end = i; break; }
    }
    if (end < 0) {
      err(`lint-refs pass 16: could not delimit the Region create at register-skills.js:${lineOf(m.index)} — ` +
          `its parens never balance. Fix the scan before trusting this gate.`);
      continue;
    }
    scanned++;
    const body = engine.slice(m.index, end + 1);
    const flags = (body.match(/flags\s*:\s*\{\s*"edha-content"\s*:\s*\{([\s\S]*)$/) || [])[1];
    if (flags === undefined) continue;                       // a Region with no edha-content flags at all
    const flagCode = stripComments(flags);
    if (!/\bhazard\s*:/.test(flagCode)) continue;            // not a hazard/terrain Region — pass 16 says nothing
    if (!/\bterrain\s*:\s*\{[^}]*\bownerUuid\s*:/.test(flagCode)) {
      err(`register-skills.js:${lineOf(m.index)} — this hazard Region does not stamp ` +
          `terrain: { ownerUuid: ... }. Every membership question in the engine ` +
          `(edhaOwnedTerrainRegions -> edhaTokenInOwnedTerrain -> the edha-zone-react ` +
          `{defeat-in-zone} sweep, edhaEnemiesInOwnedTerrain, Pack Sense, the trail dedupe) reads ` +
          `that path, so a Region without it is invisible to all of them and the gate silently ` +
          `never opens — which is exactly how Combustion Chain could never fire off a Pyre zone ` +
          `(bench run 14).`);
    }
    // A flat owner key beside it is the split vocabulary re-opening. Nested namespaces are fine, so
    // one level of sub-objects is removed before looking.
    const flat = flagCode.replace(/\b[A-Za-z_$][\w$]*\s*:\s*\{[^{}]*\}/g, "");
    const bad = flat.match(/\b([A-Za-z_$][\w$]*OwnerUuid)\s*:/);
    if (bad) {
      err(`register-skills.js:${lineOf(m.index)} — this Region writes a FLAT \`${bad[1]}\` flag. ` +
          `Terrain ownership has exactly one spelling — terrain: { ownerUuid } — and a second one ` +
          `is not a synonym: it is a Region that half the engine cannot see. Put the uuid in the ` +
          `nested object (edhaTerrainOwnerUuid is the only reader that should ever know otherwise).`);
    }
  }
  if (scanned < 5) {
    err(`lint-refs pass 16: only ${scanned} Region creates were delimited (expected 5+) — ` +
        `the scan rotted; fix it before trusting this pass.`);
  }
}

/* --- pass 17: no NUMERIC read of a system field that is an OBJECT (the object-as-scalar family) --
 *
 * Pass 11 gates "the field does not exist". This is its twin, and it cost bench run 16 three rows:
 * the field EXISTS but is a `DerivedValueField` — a SchemaField carrying {derived, override,
 * useOverride[, bonus]} plus a getter-only `.value`. `Number(thatObject)` is **NaN**, so the
 * near-universal `Number(x) || 0` idiom silently yields **0**. No error, no warning, no failed
 * promise: the mechanic simply reads as dead.
 *
 *   · edhaSpeedFt            Number(getProperty(a, "system.movement.walk.rate"))  -> 0 ft, so EVERY
 *                            `edha-move {byHalfSpeed}` moved nothing (3 pack blocks).
 *   · edhaAmbushBeliefTest   Number(…system.skills.prc.mod ?? …rank)              -> 1d20 + 0.
 *   · edhaPhantomBeliefSweep Number(…system.skills.<id>.mod ?? …rank)             -> 1d20 + 0. The
 *                            run's own targeted sweep reported "these two sites and no others";
 *                            this third one is why the check is a GATE and not a habit.
 *
 * WHAT IT CHECKS. Inside every `Number( … )` argument, every `system`-rooted property chain whose
 * LAST segment is one of the system's DerivedValueField leaf names
 * (`systemDerivedValueLeaves` in data/native-vocabulary.json, harvested from the bundle by
 * scripts/dump-native-vocabulary.js) and which does NOT terminate at .value/.override/.derived/
 * .bonus/.base. Both forms: property access (`a.system?.skills?.prc?.mod`) and the flat string
 * (`getProperty(a, "system.movement.walk.rate")`).
 *
 * WHY `Number(` AND NOT EVERY READ. `const heaMax = actor.system?.resources?.hea?.max;` is CORRECT
 * — the object is what those call sites want, and they branch on it. Only a numeric COERCION of the
 * object is the bug, and that is the decidable half.
 *
 * LIMITS, stated so a green pass is not over-read:
 *   · Leaf NAMES, not paths — `system.<anything>.mod` is checked, not just skills. That is
 *     deliberate over-approximation; the fix (`edhaDerivedNum`) is right for all of them anyway.
 *   · Only inside a literal `Number(...)`. `+x` and `x * 2` on a derived object are the same bug
 *     and are NOT caught. Every site in the engine today uses Number().
 *   · `system.defenses.<phy|cog|spi>` is a DerivedValueField too, but the system builds those three
 *     anonymously, so the dumper cannot name them (see its block comment).
 *   · Skipped with a warning when the snapshot predates the leaf list — warn, don't guess. */
{
  const SNAP17 = path.join(REPO_ROOT, "data", "native-vocabulary.json");
  let leaves = null;
  try {
    const v = JSON.parse(fs.readFileSync(SNAP17, "utf8"));
    if (Array.isArray(v.systemDerivedValueLeaves) && v.systemDerivedValueLeaves.length >= 8) leaves = new Set(v.systemDerivedValueLeaves);
    else console.warn("⚠ lint-refs pass 17: native-vocabulary.json has no systemDerivedValueLeaves — object-as-scalar checking SKIPPED. Regenerate with: node scripts/dump-native-vocabulary.js");
  } catch (e) { /* pass 2's block already warned about an unreadable snapshot */ }

  if (leaves) {
    const TERMINAL = new Set(["value", "override", "derived", "bonus", "base"]);
    const lineOf17 = (idx) => engine.slice(0, idx).split("\n").length;
    // Two views of the SAME offsets (blankStringsAndComments preserves them, which is the whole
    // point of that helper): balance parens on the fully-blanked copy so a ")" inside a string
    // cannot close the call early, then read the argument out of the copy that KEPT string bodies —
    // the flat `"system.movement.walk.rate"` form lives inside a string.
    const blank17 = blankStringsAndComments(engine);
    const src17 = blankStringsAndComments(engine, { keepStrings: true });
    const matchParen = (s, start) => {                       // s[start] must be "("
      let depth = 0;
      for (let i = start; i < s.length; i++) {
        if (s[i] === "(") depth++;
        else if (s[i] === ")") { depth--; if (depth === 0) return i; }
      }
      return -1;
    };
    let scanned = 0;

    const flag = (line, path_, last) =>
      err(`register-skills.js:${line}: \`${path_}\` is coerced with Number(), but \`${last}\` is a ` +
          `cosmere DerivedValueField — an OBJECT ({derived, override, useOverride[, bonus]} + a ` +
          `getter-only .value), so Number() is NaN and the \`|| 0\` next to it silently yields 0. ` +
          `Read it through edhaDerivedNum(v, fallback), which takes .value first. Three engine ` +
          `sites shipped this way and every one of them read as a dead mechanic, not as an error.`);

    for (const m of blank17.matchAll(/\bNumber\s*\(/g)) {
      const open = blank17.indexOf("(", m.index);
      const close = matchParen(blank17, open);
      if (close < 0) continue;
      const arg = src17.slice(open + 1, close);
      const argCode = blank17.slice(open + 1, close);   // strings blanked: a path QUOTED IN PROSE is form (b)'s job, not (a)'s
      scanned++;
      // (a) property access — system.a?.b.c ; the chain may use ?. and [expr] segments.
      for (const c of argCode.matchAll(/\bsystem(?:\s*\?\.\s*|\s*\.\s*)(?:[A-Za-z_$][\w$]*|\[[^\]]*\])(?:(?:\s*\?\.\s*|\s*\.\s*)(?:[A-Za-z_$][\w$]*|\[[^\]]*\])|\?\.\[[^\]]*\])*/g)) {
        const segs = c[0].split(/\s*\??\.\s*/).filter(Boolean);
        const last = segs[segs.length - 1];
        if (last && !last.startsWith("[") && leaves.has(last) && !TERMINAL.has(last)) {
          flag(lineOf17(open + 1 + c.index), c[0].replace(/\s+/g, ""), last);
        }
      }
      // (b) flat string paths — getProperty(a, "system.movement.walk.rate"), update keys, templates.
      for (const c of arg.matchAll(/["'`]system\.([\w$.${}[\]]*)/g)) {
        const segs = c[1].split(".").filter(Boolean);
        const last = segs[segs.length - 1];
        if (last && leaves.has(last) && !TERMINAL.has(last)) {
          flag(lineOf17(open + 1 + c.index), `system.${c[1]}`, last);
        }
      }
    }
    // Rot alarm: the engine has hundreds of Number() calls. A regex that stops matching them turns
    // this pass into a silent no-op, which is worse than not having it.
    if (scanned < 100) {
      err(`lint-refs pass 17: only ${scanned} Number() calls were delimited (expected 100+) — the scan rotted; fix it before trusting this pass.`);
    }
  }
}

/* --- pass 18: a registered event type must be able to FIRE (the dead-event family, 07-28) -------
 *
 * Bench run 17: Cinderbrock's Fire the Wrack placed nothing — five drives, no card, no error. Its
 * rule sat on `edha-pre-use`, which the engine registered with the sentinel hook
 * `edha-content.noop-pre-use` and then never fired. The type showed up in Ben's Events-tab dropdown
 * looking exactly like a working one, and anything authored onto it was silently inert. Same shape
 * as CASE_STUDIES §8 (The Seeming): "registered" is a claim about a code PATH, not a code LINE.
 *
 * WHAT IT CHECKS. Every `registerItemEventType` whose `hook` is a sentinel (`edha-content.noop-*`)
 * must have ONE of:
 *   (a) the engine fires that hook — `Hooks.call/callAll("<hook>"` — so the system's own event
 *       framework dispatches it (this is what `edha-pre-use` now does); or
 *   (b) the engine names the event TYPE outside its own registration, i.e. a dispatcher that
 *       enumerates rules with `rule.event === "<type>"` (edha-on-hit, edha-test-success, …); or
 *   (c) the type is a declared SHELF below — a config-only event whose rules are read by HANDLER
 *       type rather than by event, which is a legitimate second idiom in this engine
 *       (`edhaRuleOf(item, "<handlerType>")` and `edhaWatchersOfRule("<handlerType>")` both ignore
 *       the `event` field entirely). Each shelf names its reader so the claim is checkable.
 *
 * A NEW sentinel event type therefore FAILS until it is either fired or declared — which is the
 * half that matters, because the trap is invisible from the data side.
 *
 * LIMIT, stated so a green pass is not over-read: this gates the EVENT, not the (event, handler)
 * PAIR. Fire the Wrack's real defect was a pair — `edha-place-hazard` had no pre-use reader while
 * `edha-burst` did — and a pair-level check is NOT reliably decidable by grep: a reachability
 * matrix built for this pass flagged 44 pairs, of which the great majority are false positives
 * (`edha-damage-rider` × 27 is read via `h?.type !== "edha-damage-rider"`; `edha-watch` × 14 via
 * `edhaWatchersOfRule`), while Fire the Wrack itself came back FALSE-NEGATIVE — matching
 * `edhaTrailRuleOf`'s `type === "edha-place-hazard" && h.mode === "trail"`, a movement-driven
 * reader that never runs for its `mode: "drop"` rule. A gate that noisy teaches people to ignore
 * it. Pair-level reachability is filed as backlog with that matrix as the evidence. */
{
  /* Config-only shelves: the event carries the rule, a handler-type reader runs it. Reader named. */
  const SENTINEL_SHELVES = {
    "edha-apply-watch":     "read by handler type — edhaWatchersOfRule / the applyDamage cue sweep (edha-gm-cue, edha-overflow-thp, …)",
    "edha-pre-deal-damage": "read by handler type — the rollDamage wrapper scans edha-damage-rider rules",
    "edha-pre-test":        "read by handler type — the pre{Skill|Attack|Item}Roll injector scans edha-test-rider rules",
    "edha-watch-rule":      "read by handler type — edhaWatchersOfRule(<handlerType>), which ignores the event field by design",
  };
  const src18 = blankStringsAndComments(engine, { keepStrings: true });   // comments out, strings kept
  const types = [...src18.matchAll(/registerItemEventType\(\{[\s\S]{0,400}?type:\s*"(edha-[a-z0-9-]+)"[\s\S]{0,800}?hook:\s*"([^"]+)"/g)]
    .map((m) => ({ type: m[1], hook: m[2] }));
  if (types.length < 10) {
    err(`lint-refs pass 18: only ${types.length} registerItemEventType calls were parsed (expected 10+) — the scan rotted; fix it before trusting this pass.`);
  }
  for (const { type, hook } of types) {
    if (!/^edha-content\.noop-/.test(hook)) continue;                 // a real system hook fires itself
    const fired = src18.includes(`Hooks.callAll("${hook}"`) || src18.includes(`Hooks.call("${hook}"`);
    if (fired) continue;
    // (b) the type named anywhere OTHER than inside its own registration block
    const occurrences = [...src18.matchAll(new RegExp(`"${type.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}"`, "g"))];
    const namedOutsideRegistration = occurrences.length > 1;
    if (namedOutsideRegistration) continue;
    if (SENTINEL_SHELVES[type]) continue;
    err(`lint-refs pass 18: event type "${type}" is registered with the sentinel hook "${hook}" but nothing can ever dispatch it — ` +
        `no Hooks.call("${hook}"), no dispatcher naming "${type}", and it is not a declared shelf. ` +
        `Authoring a rule onto it is a silent no-op (bench run 17, Fire the Wrack). Fire the hook from its real trigger, ` +
        `add a dispatcher, or declare it in SENTINEL_SHELVES with the handler-type reader that runs its rules.`);
  }
}

// --- report --------------------------------------------------------------------
if (errors.length) {
  for (const e of errors) console.error(`✗ ${e}`);
  console.error(`\n${errors.length} error${errors.length === 1 ? "" : "s"}.`);
  process.exit(1);
}
console.log(`✓ lint-refs: ${talentNames.size} talent names, ${nameLits.size} engine name-literals resolved, authored overlays clean.`);
