"""Resolve the bookkeeping conflicts of `git merge origin/main` inside a worker's worktree.
Run from the worktree root after a conflicted merge (HEAD = the worker's branch tip, detached).
- the month changelog: main's file + the branch's own new deltas re-inserted at the top, recount
- its README row: recount
- generated files (dashboard, assembled engine, pm-state): main's copy, regenerated by the caller
- the checklist, the TODO file, the audit ledger, the rulings, ENGINE_INDEX, CLAUDE.md: main's copy
  with the branch's edits REPLAYED onto it line by line (difflib opcodes base → branch, applied
  to main by exact line match); any edit whose context is not found in main → exit 2, named
Anything else conflicted → exit 2 and name it."""
import difflib, io, re, subprocess, sys

def sh(*a): return subprocess.check_output(a).decode("utf-8")
def show(ref, path): return sh("git", "show", ref + ":" + path)
def nl(s): return "\r\n" if "\r\n" in s[:5000] else "\n"
def wr(p, s): io.open(p, "w", encoding="utf-8", newline="").write(s)

MAIN_REF = "origin/main"
CL = "docs/handoff-changelog/2026-09.md"; RM = "docs/handoff-changelog/README.md"
MARK = "<!-- handoff-split: dated deltas begin below this line, verbatim, newest first -->"
GENERATED = ["EDHA_DASHBOARD.html", "module-src/scripts/register-skills.js", "docs/pm-state.json", "EDHA_PLAYER_PRIMER.html", "EDHA_CANON_CODEX.html", "docs/analysis/bestiary/CENSUS.md"]
REPLAY = ["EDHA_FOUNDRY_TEST_CHECKLIST.md", "TODO_REPO_HYGIENE.md", "docs/analysis/rules-audit-2026-09.md", "EDHA_RULINGS.md",
          ".claude/skills/leyline-tree-authoring/ENGINE_INDEX.md", "CLAUDE.md", "scripts/README.md", ".claude/skills/phrasing-verifier/SKILL.md", ".claude/skills/leyline-revision-guide/SKILL.md", ".claude/skills/deity-revision-guide/SKILL.md", "docs/ACTOR_STAT_DERIVATION.md"]

conflicted = [l for l in sh("git", "diff", "--name-only", "--diff-filter=U").split("\n") if l.strip()]
print("conflicted:", conflicted)
base = sh("git", "merge-base", "HEAD", MAIN_REF).strip()

def deltas(text):
    t = text.replace("\r\n", "\n"); i = t.find(MARK); body = t[i + len(MARK):]
    out = []
    for p in re.split(r"(?m)^(?=## 2026-)", body):
        if p.startswith("## 2026-"): out.append((p.split("\n", 1)[0], p if p.endswith("\n\n") else p.rstrip("\n") + "\n\n"))
    return out

def replay(path):
    """main's version with the branch's (base → HEAD) line edits applied by exact match."""
    b = show(base, path).replace("\r\n", "\n").split("\n"); h = show("HEAD", path).replace("\r\n", "\n").split("\n")
    m_raw = show(MAIN_REF, path); e = nl(m_raw); m = m_raw.replace("\r\n", "\n").split("\n")
    sm = difflib.SequenceMatcher(None, b, h, autojunk=False)
    def find(seq, start_hint=0):
        n = len(seq)
        if n == 0: return None
        for i in range(len(m) - n + 1):
            if m[i:i + n] == seq: return i
        return None
    ops = [op for op in sm.get_opcodes() if op[0] != "equal"]
    for tag, i1, i2, j1, j2 in reversed(ops):   # apply bottom-up so earlier indices stay valid
        old = b[i1:i2]; new = h[j1:j2]
        if tag in ("replace", "delete"):
            pos = find(old)
            if pos is None: raise RuntimeError("%s: cannot find the %d line(s) the branch %sd, starting %r" % (path, len(old), tag, old[0][:80]))
            m[pos:pos + len(old)] = new
        else:  # insert: anchor on the preceding base line (or the following one at the top)
            if i1 > 0:
                ctx = b[i1 - 1]; pos = find([ctx])
                if pos is None: raise RuntimeError("%s: cannot find the anchor line before an insertion: %r" % (path, ctx[:80]))
                m[pos + 1:pos + 1] = new
            else:
                m[0:0] = new
    return e.join(m)

handled = set()
if CL in conflicted or RM in conflicted:
    main_cl = show(MAIN_REF, CL); e = nl(main_cl)
    branch_cl = show("HEAD", CL); base_cl = show(base, CL)
    base_heads = {h for h, _ in deltas(base_cl)}; main_heads = {h for h, _ in deltas(main_cl)}
    new = [(h, b) for h, b in deltas(branch_cl) if h not in base_heads and h not in main_heads]
    mm = re.search(r"\((\d+) deltas, 2026-09-04 → 2026-09-16\)", main_cl); n = int(mm.group(1))
    out = main_cl.replace(mm.group(0), "(%d deltas, 2026-09-04 → 2026-09-16)" % (n + len(new)), 1)
    mk = MARK + e + e; assert mk in out
    out = out.replace(mk, mk + "".join(b for _, b in new).replace("\n", e), 1); wr(CL, out)
    rd = show(MAIN_REF, RM)
    m2 = re.search(r"\| \[`2026-09\.md`\]\(2026-09\.md\) \| (\d+) \| 2026-09-04 → 2026-09-16 \|", rd); assert int(m2.group(1)) == n, (m2.group(1), n)
    wr(RM, rd.replace(m2.group(0), "| [`2026-09.md`](2026-09.md) | %d | 2026-09-04 → 2026-09-16 |" % (n + len(new)), 1))
    print("changelog: %d new delta(s) re-inserted; count %d -> %d" % (len(new), n, n + len(new))); handled |= {CL, RM}
for g in GENERATED:
    if g in conflicted:
        subprocess.check_call(["git", "checkout", "--theirs", g]); handled.add(g); print("generated, main's copy (regenerate):", g)
for path in REPLAY:
    if path in conflicted:
        try:
            wr(path, replay(path)); handled.add(path); print("replayed the branch's edits onto main's copy:", path)
        except RuntimeError as err:
            print("REPLAY FAILED:", err)
rest = [c for c in conflicted if c not in handled]
if rest:
    print("UNHANDLED conflicts:", rest); sys.exit(2)
print("RESOLVED")
